// Generated by tools/ml/generate_bindings.py from artifacts/models/manifest.json. Do not edit.

package com.sennnen.mav.ml

/**
 * The TensorFlow Lite artefacts this build ships, and the tensor contract each binds to.
 *
 * `admittedSha256` is the hash of the asset as packaged. The runner hashes the mapped
 * buffer at load and refuses a model whose bytes are not this value, so a swapped asset
 * fails at open rather than producing an unattributable number.
 *
 * `acceleratesWell` carries the decision the Core ML conversion made by measurement:
 * true where the model was admitted at half-precision arithmetic, false where it had to
 * keep full width to stay near its reference. Android has no equivalent measurement at
 * runtime, and every accelerator here is half-precision hardware, so the same answer
 * decides whether MavModelAcceleration offers this model the GPU. That is what keeps
 * the two platforms computing the same arithmetic from the same weights.
 *
 * `preferredPath` is where the model actually runs here, and unlike the flag above it
 * was measured on hardware rather than inferred from iOS. The inference was wrong:
 * "float16" is not one behaviour across platforms — Apple's Neural Engine accumulates
 * a half-width matmul into a wider register and the GPU delegate does not — and the
 * delegate also turned out slower than the CPU on all but one of these graphs. The CPU
 * is therefore the default, and a model leaves it only where a sweep measured the GPU
 * both faster and no less accurate. tools/ml/android_delegate.py writes the decision;
 * artifacts/models/android_delegate.json records the measurements behind it.
 */
internal object MavModelCatalog {
    data class TensorSpec(val name: String, val shape: IntArray) {
        val elementCount: Int get() = shape.fold(1) { total, side -> total * side }

        override fun equals(other: Any?): Boolean =
            other is TensorSpec && name == other.name && shape.contentEquals(other.shape)

        override fun hashCode(): Int = 31 * name.hashCode() + shape.contentHashCode()
    }

    data class Entry(
        val slug: String,
        val assetPath: String,
        val admittedSha256: String,
        val acceleratesWell: Boolean,
        val preferredPath: MavModelAcceleration.Path,
        val inputs: List<TensorSpec>,
        val outputs: List<TensorSpec>,
    )

    val entries: Map<String, Entry> = mapOf(
        "activity_context_embedding" to Entry(
            slug = "activity_context_embedding",
            assetPath = "models/activity_context_embedding.tflite",
            admittedSha256 = "842ad2d5f75280f219eaac1a39205dc7ba63151e2fcbddf485ffa82de8fd9f69",
            acceleratesWell = true,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("context", intArrayOf(1, 16, 85)),
            ),
            outputs = listOf(
                TensorSpec("embeddings", intArrayOf(1, 16, 312)),
            ),
        ),
        "activity_detection" to Entry(
            slug = "activity_detection",
            assetPath = "models/activity_detection.tflite",
            admittedSha256 = "5bb6e57ca16bf5f328f0e1b5c5e74f6a03b2d0b5f7b653941f97a4b94d16a197",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("features", intArrayOf(1, 64, 77)),
            ),
            outputs = listOf(
                TensorSpec("activity_output", intArrayOf(1, 64, 262)),
            ),
        ),
        "activity_ensemble" to Entry(
            slug = "activity_ensemble",
            assetPath = "models/activity_ensemble.tflite",
            admittedSha256 = "d3a0e319b063850f6cb06ce09de4a23bb988cc520e8f61376ec1000cb4ca5ba1",
            acceleratesWell = true,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("primary", intArrayOf(1, 16, 260)),
                TensorSpec("secondary", intArrayOf(1, 16, 260)),
            ),
            outputs = listOf(
                TensorSpec("segment_output", intArrayOf(1, 16, 260)),
            ),
        ),
        "activity_history_transformer" to Entry(
            slug = "activity_history_transformer",
            assetPath = "models/activity_history_transformer.tflite",
            admittedSha256 = "5ae0d644ed116890d069136bfff653feaf48522141c492aa43f886c0fab4ea63",
            acceleratesWell = true,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("segments", intArrayOf(1, 16, 573)),
            ),
            outputs = listOf(
                TensorSpec("encoded", intArrayOf(1, 16, 336)),
                TensorSpec("attention", intArrayOf(1, 1, 6, 16, 18)),
            ),
        ),
        "activity_primary_segments" to Entry(
            slug = "activity_primary_segments",
            assetPath = "models/activity_primary_segments.tflite",
            admittedSha256 = "94267d6c57de8253298322b28548fe53a9c1d546a2d87b1d695c6482f27f8fc1",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("features", intArrayOf(1, 16, 110)),
            ),
            outputs = listOf(
                TensorSpec("segment_output", intArrayOf(1, 16, 260)),
            ),
        ),
        "activity_secondary_segments" to Entry(
            slug = "activity_secondary_segments",
            assetPath = "models/activity_secondary_segments.tflite",
            admittedSha256 = "32b2ed7dbd81a4433763be53bc627da9fa89d300a7fa7dd7f107f969176a75bb",
            acceleratesWell = true,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("features", intArrayOf(1, 16, 336)),
            ),
            outputs = listOf(
                TensorSpec("segment_output", intArrayOf(1, 16, 260)),
            ),
        ),
        "activity_transition" to Entry(
            slug = "activity_transition",
            assetPath = "models/activity_transition.tflite",
            admittedSha256 = "4eb572738b956f0f79c28a59dbd1b7dd8b96c01767171c23856deca123ef9252",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("features", intArrayOf(1, 64, 29)),
            ),
            outputs = listOf(
                TensorSpec("transition_logits", intArrayOf(1, 64)),
            ),
        ),
        "awhr_imputation" to Entry(
            slug = "awhr_imputation",
            assetPath = "models/awhr_imputation.tflite",
            admittedSha256 = "9a621a3f9741a06466943b1800e38a0319d85a765bfe12e04a7cfc967458ea32",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("window", intArrayOf(1, 60, 13)),
            ),
            outputs = listOf(
                TensorSpec("imputed_hr", intArrayOf(1, 60, 1)),
            ),
        ),
        "awhr_profile_core" to Entry(
            slug = "awhr_profile_core",
            assetPath = "models/awhr_profile_core.tflite",
            admittedSha256 = "17efde1ac12f65c4b59033efd4714beb28b943d741dbe4ae95e46458a933483e",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("features", intArrayOf(60, 19)),
            ),
            outputs = listOf(
                TensorSpec("profile_features", intArrayOf(60, 6)),
            ),
        ),
        "awhr_profile_head" to Entry(
            slug = "awhr_profile_head",
            assetPath = "models/awhr_profile_head.tflite",
            admittedSha256 = "f69957dd7f3b6c1d48c68d166c5b7ca04f0ee3437469b2880b0a876420a16fd3",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("features", intArrayOf(60, 32)),
            ),
            outputs = listOf(
                TensorSpec("profile_logits", intArrayOf(60, 3)),
            ),
        ),
        "awhr_profile_recurrent" to Entry(
            slug = "awhr_profile_recurrent",
            assetPath = "models/awhr_profile_recurrent.tflite",
            admittedSha256 = "bdb3e5b14e4bcb89e9e07b854876d931b6a90114ca2cb2726d8fa1b7d8ab5dcb",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("features", intArrayOf(1, 60, 6)),
            ),
            outputs = listOf(
                TensorSpec("encoded", intArrayOf(1, 60, 32)),
            ),
        ),
        "behavior_embedding" to Entry(
            slug = "behavior_embedding",
            assetPath = "models/behavior_embedding.tflite",
            admittedSha256 = "c4071ac408da7dc1cdbd4b9fc6ca001c6be13e422d94114bb546020dbf3e0667",
            acceleratesWell = true,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("behavior_ids", intArrayOf(1, 16)),
            ),
            outputs = listOf(
                TensorSpec("embeddings", intArrayOf(1, 16, 256)),
            ),
        ),
        "cva_encoder" to Entry(
            slug = "cva_encoder",
            assetPath = "models/cva_encoder.tflite",
            admittedSha256 = "4fbe89e6db08c5da8a0e98f3ff330cf81f9c4cab58c835d734f3e5559e462826",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("pulses", intArrayOf(1, 1024)),
            ),
            outputs = listOf(
                TensorSpec("embeddings", intArrayOf(1, 128)),
            ),
        ),
        "cva_predictor_v1_base" to Entry(
            slug = "cva_predictor_v1_base",
            assetPath = "models/cva_predictor_v1_base.tflite",
            admittedSha256 = "9bc367f802d4bb684fd08a882de8c9af12b234ff1ed85e9d779b7164c98a05f4",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("pulse_triple", intArrayOf(1, 3, 256)),
                TensorSpec("exogenous", intArrayOf(1, 8)),
            ),
            outputs = listOf(
                TensorSpec("cva", intArrayOf(1, 1)),
                TensorSpec("pwv", intArrayOf(1, 1)),
                TensorSpec("features", intArrayOf(1, 272)),
            ),
        ),
        "cva_probes_female" to Entry(
            slug = "cva_probes_female",
            assetPath = "models/cva_probes_female.tflite",
            admittedSha256 = "b328ed6e5b8de4777448c1405ad6364f469c839a2c6497fed88670d78dc64f74",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("embeddings", intArrayOf(1, 128)),
                TensorSpec("age", intArrayOf(1)),
                TensorSpec("weight", intArrayOf(1)),
                TensorSpec("bmi", intArrayOf(1)),
            ),
            outputs = listOf(
                TensorSpec("cva", intArrayOf(1)),
                TensorSpec("pwv", intArrayOf(1)),
                TensorSpec("systolic", intArrayOf(1)),
                TensorSpec("diastolic", intArrayOf(1)),
            ),
        ),
        "cva_probes_male" to Entry(
            slug = "cva_probes_male",
            assetPath = "models/cva_probes_male.tflite",
            admittedSha256 = "fd4b9a282f00d8457aa981a6d0ae5e7cb3c806a859bf325cbb6c473c93f5503c",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("embeddings", intArrayOf(1, 128)),
                TensorSpec("age", intArrayOf(1)),
                TensorSpec("weight", intArrayOf(1)),
                TensorSpec("bmi", intArrayOf(1)),
            ),
            outputs = listOf(
                TensorSpec("cva", intArrayOf(1)),
                TensorSpec("pwv", intArrayOf(1)),
                TensorSpec("systolic", intArrayOf(1)),
                TensorSpec("diastolic", intArrayOf(1)),
            ),
        ),
        "dhrv_imputation" to Entry(
            slug = "dhrv_imputation",
            assetPath = "models/dhrv_imputation.tflite",
            admittedSha256 = "acb2e38d48aa8789f39692b933d08f668f2402545d92a97cecb8c7b8b2127f45",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("features", intArrayOf(1, 10)),
            ),
            outputs = listOf(
                TensorSpec("imputed_dhrv", intArrayOf(1, 1)),
            ),
        ),
        "energy_expenditure_hr" to Entry(
            slug = "energy_expenditure_hr",
            assetPath = "models/energy_expenditure_hr.tflite",
            admittedSha256 = "55874df93c68b2c393262d13d5da3bb2bc13ee3a074ae9629188ab39b813cf01",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("features", intArrayOf(1, 50)),
            ),
            outputs = listOf(
                TensorSpec("energy", intArrayOf(1, 1)),
            ),
        ),
        "energy_expenditure_no_hr" to Entry(
            slug = "energy_expenditure_no_hr",
            assetPath = "models/energy_expenditure_no_hr.tflite",
            admittedSha256 = "6bf1ae7f18ca18ec7c3ae216f754beff38374cfa4ff7f4ab9ebe5af1d9fc9003",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("features", intArrayOf(1, 42)),
            ),
            outputs = listOf(
                TensorSpec("energy", intArrayOf(1, 1)),
            ),
        ),
        "halite_ppg_score" to Entry(
            slug = "halite_ppg_score",
            assetPath = "models/halite_ppg_score.tflite",
            admittedSha256 = "59fa620a549d1cce51d23876c7b7f990a51bae17411d7b22cd13a728a16688bc",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("embeddings", intArrayOf(1, 256)),
            ),
            outputs = listOf(
                TensorSpec("ppg_score", intArrayOf(1, 1)),
            ),
        ),
        "halite_risk_tree" to Entry(
            slug = "halite_risk_tree",
            assetPath = "models/halite_risk_tree.tflite",
            admittedSha256 = "b7d4e75090e2dd98067277a2ad7572bd6f0ede686addc80416461f002d08d4a5",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("features", intArrayOf(1, 13)),
            ),
            outputs = listOf(
                TensorSpec("label", intArrayOf(1)),
                TensorSpec("probabilities", intArrayOf(1, 2)),
            ),
        ),
        "illness_detection" to Entry(
            slug = "illness_detection",
            assetPath = "models/illness_detection.tflite",
            admittedSha256 = "6f8e91b7bd653c1fc6a1b210e46819eb62dc5f55ed973ff8a3c3cad96d5246d0",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("scalars", intArrayOf(1, 4)),
                TensorSpec("time_series", intArrayOf(1, 8, 30)),
            ),
            outputs = listOf(
                TensorSpec("illness_probability", intArrayOf(1, 1)),
            ),
        ),
        "popsicle_min_follicular" to Entry(
            slug = "popsicle_min_follicular",
            assetPath = "models/popsicle_min_follicular.tflite",
            admittedSha256 = "54c55f54ab37cfb603a38da64528f817e227122e55fbadfe35cf9b2a168bb69f",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("features", intArrayOf(1, 9)),
            ),
            outputs = listOf(
                TensorSpec("min_follicular_days", intArrayOf(1, 1)),
            ),
        ),
        "popsicle_min_follicular_v16" to Entry(
            slug = "popsicle_min_follicular_v16",
            assetPath = "models/popsicle_min_follicular_v16.tflite",
            admittedSha256 = "54c55f54ab37cfb603a38da64528f817e227122e55fbadfe35cf9b2a168bb69f",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("features", intArrayOf(1, 9)),
            ),
            outputs = listOf(
                TensorSpec("min_follicular_days", intArrayOf(1, 1)),
            ),
        ),
        "popsicle_ovulation_detection" to Entry(
            slug = "popsicle_ovulation_detection",
            assetPath = "models/popsicle_ovulation_detection.tflite",
            admittedSha256 = "7ff9f985b7542f0865d1ae32cc8a0ff4bb17bd82441471dd13efa380c50a35a0",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("time_series", intArrayOf(1, 40, 3)),
                TensorSpec("scalars", intArrayOf(1, 40, 4)),
            ),
            outputs = listOf(
                TensorSpec("ovulation_probability", intArrayOf(1, 40, 1)),
            ),
        ),
        "popsicle_ovulation_detection_v16" to Entry(
            slug = "popsicle_ovulation_detection_v16",
            assetPath = "models/popsicle_ovulation_detection_v16.tflite",
            admittedSha256 = "2e244193a3069b632c00934a15f506f6e8de7efd7adae9b50dd1ea1e04077054",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("time_series", intArrayOf(1, 40, 3)),
                TensorSpec("scalars", intArrayOf(1, 40, 4)),
            ),
            outputs = listOf(
                TensorSpec("ovulation_probability", intArrayOf(1, 40, 1)),
            ),
        ),
        "popsicle_ovulation_prediction" to Entry(
            slug = "popsicle_ovulation_prediction",
            assetPath = "models/popsicle_ovulation_prediction.tflite",
            admittedSha256 = "3ff28f25ad2559d068126d41a469f22a0d18be735f32a86437e9aee96cbbaf3f",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("time_series", intArrayOf(1, 40, 3)),
                TensorSpec("scalars", intArrayOf(1, 40, 4)),
            ),
            outputs = listOf(
                TensorSpec("days", intArrayOf(1, 40, 1)),
            ),
        ),
        "popsicle_ovulation_prediction_v16" to Entry(
            slug = "popsicle_ovulation_prediction_v16",
            assetPath = "models/popsicle_ovulation_prediction_v16.tflite",
            admittedSha256 = "d8139c89cf715f16b6a9c41e54b3e5f849c75f908bc8462ff7a019cf670cc9bc",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("time_series", intArrayOf(1, 40, 3)),
                TensorSpec("scalars", intArrayOf(1, 40, 4)),
            ),
            outputs = listOf(
                TensorSpec("days", intArrayOf(1, 40, 1)),
            ),
        ),
        "popsicle_period_prediction" to Entry(
            slug = "popsicle_period_prediction",
            assetPath = "models/popsicle_period_prediction.tflite",
            admittedSha256 = "aa3265e7c82faa1a19f46fc1594ae49cd6a5faad439b992150d31ca9e1e2c1e5",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("time_series", intArrayOf(1, 40, 3)),
                TensorSpec("scalars", intArrayOf(1, 40, 4)),
            ),
            outputs = listOf(
                TensorSpec("days", intArrayOf(1, 40, 1)),
            ),
        ),
        "popsicle_period_prediction_v16" to Entry(
            slug = "popsicle_period_prediction_v16",
            assetPath = "models/popsicle_period_prediction_v16.tflite",
            admittedSha256 = "f6853eadbab0f79d77d65f5bdf3928ddbacf42f89b021217a481bf1e746ebc00",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("time_series", intArrayOf(1, 40, 3)),
                TensorSpec("scalars", intArrayOf(1, 40, 4)),
            ),
            outputs = listOf(
                TensorSpec("days", intArrayOf(1, 40, 1)),
            ),
        ),
        "pulse_ppg" to Entry(
            slug = "pulse_ppg",
            assetPath = "models/pulse_ppg.tflite",
            admittedSha256 = "4d6359ab1e37d7a47bb4ff94ca74fe2b19604283dcdece0a256a48ea440c78fb",
            acceleratesWell = true,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("ppg", intArrayOf(1, 1, 12000)),
            ),
            outputs = listOf(
                TensorSpec("embeddings", intArrayOf(1, 512)),
            ),
        ),
        "pulsenet_foundation" to Entry(
            slug = "pulsenet_foundation",
            assetPath = "models/pulsenet_foundation.tflite",
            admittedSha256 = "7f7860c0ad92c14772af463a678a9df35f0034bff566e792e8cc491c9d1f6ad8",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("ppg", intArrayOf(1, 1, 1500)),
            ),
            outputs = listOf(
                TensorSpec("embeddings", intArrayOf(1, 256)),
            ),
        ),
        "sleepnet_bdi" to Entry(
            slug = "sleepnet_bdi",
            assetPath = "models/sleepnet_bdi.tflite",
            admittedSha256 = "590469f28981207650001b833089219386284383ede29fda9d64f56465659769",
            acceleratesWell = true,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("high_res", intArrayOf(1, 115200, 2)),
            ),
            outputs = listOf(
                TensorSpec("staging_logits", intArrayOf(1, 4, 1800)),
                TensorSpec("apnea_logits", intArrayOf(1, 1, 1800)),
            ),
        ),
        "sleepnet_bdi_v3" to Entry(
            slug = "sleepnet_bdi_v3",
            assetPath = "models/sleepnet_bdi_v3.tflite",
            admittedSha256 = "dd144e71757fe443b587f95b947a89c54790654d8c5eef9392adae97f5e7b4a4",
            acceleratesWell = true,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("high_res", intArrayOf(1, 115200, 2)),
            ),
            outputs = listOf(
                TensorSpec("staging_logits", intArrayOf(1, 4, 1800)),
                TensorSpec("apnea_logits", intArrayOf(1, 1, 1800)),
            ),
        ),
        "sleepnet_moonstone" to Entry(
            slug = "sleepnet_moonstone",
            assetPath = "models/sleepnet_moonstone.tflite",
            admittedSha256 = "ae635931514d09f53607b80acc72acae36038b3f16c12e7d0ad2abac8b277d2d",
            acceleratesWell = true,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("high_res", intArrayOf(1, 115200, 3)),
                TensorSpec("low_res", intArrayOf(1, 1800, 1)),
            ),
            outputs = listOf(
                TensorSpec("staging_logits", intArrayOf(1, 4, 1800)),
                TensorSpec("apnea_logits", intArrayOf(1, 1, 1800)),
            ),
        ),
        "source_embedding" to Entry(
            slug = "source_embedding",
            assetPath = "models/source_embedding.tflite",
            admittedSha256 = "84a1d9a9b6fa7c6523912801190faece00c579afa6c59e66fb145de4c35d14b8",
            acceleratesWell = true,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("source_ids", intArrayOf(1, 16)),
            ),
            outputs = listOf(
                TensorSpec("source_features", intArrayOf(1, 16, 8)),
            ),
        ),
        "step_eligibility" to Entry(
            slug = "step_eligibility",
            assetPath = "models/step_eligibility.tflite",
            admittedSha256 = "b33af52edeaa6671af7cd9075308c8d986e3ea5b4cf964244b4f8a562eefff68",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("motion", intArrayOf(1, 19)),
            ),
            outputs = listOf(
                TensorSpec("eligibility_features", intArrayOf(1, 4)),
            ),
        ),
        "step_head" to Entry(
            slug = "step_head",
            assetPath = "models/step_head.tflite",
            admittedSha256 = "09f1045c6644d8b6296b5a80132f9be20267ffda0187791bf824ad92a7d75008",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("eligibility_features", intArrayOf(1, 4)),
            ),
            outputs = listOf(
                TensorSpec("eligibility", intArrayOf(1, 1)),
            ),
        ),
        "step_multiplier" to Entry(
            slug = "step_multiplier",
            assetPath = "models/step_multiplier.tflite",
            admittedSha256 = "fb966f78975654198304b8391c1827b423427962acf262f08ed6748c5b37abbb",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("eligibility", intArrayOf(1, 1)),
            ),
            outputs = listOf(
                TensorSpec("multiplier", intArrayOf(1, 1)),
            ),
        ),
        "whr_unet_encoder" to Entry(
            slug = "whr_unet_encoder",
            assetPath = "models/whr_unet_encoder.tflite",
            admittedSha256 = "77d297aa6b3eb1e012c3a6d36ac73004788b367e689b9bc7282326f1f506805f",
            acceleratesWell = true,
            preferredPath = MavModelAcceleration.Path.GPU_FULL,
            inputs = listOf(
                TensorSpec("images", intArrayOf(1, 4, 128, 128)),
            ),
            outputs = listOf(
                TensorSpec("features", intArrayOf(1, 2, 128, 128)),
            ),
        ),
        "whr_unet_head" to Entry(
            slug = "whr_unet_head",
            assetPath = "models/whr_unet_head.tflite",
            admittedSha256 = "e9285794934e2b53f5d6b2c2301e4e88cbc718f1ce34fbfce19b8155dc0942d7",
            acceleratesWell = false,
            preferredPath = MavModelAcceleration.Path.CPU,
            inputs = listOf(
                TensorSpec("vectors", intArrayOf(1, 1, 128)),
                TensorSpec("scalars", intArrayOf(1, 7)),
                TensorSpec("features", intArrayOf(1, 2, 128, 128)),
            ),
            outputs = listOf(
                TensorSpec("heart_rate", intArrayOf(1, 2, 128)),
            ),
        ),
    )

    val slugs: List<String> = entries.keys.toList()
}
