#!/usr/bin/env python3
"""Generate the model registry that Rust, Swift and Kotlin all read from one manifest.

Three languages need the same facts about every model: its slug, its tensor shapes, and
the SHA-256 of the artefact each platform loads. Hand-maintaining that in three places is
how a build ends up admitting a hash that is no longer in the bundle, so all three are
generated here from `artifacts/models/manifest.json`.

    python tools/ml/generate_bindings.py [--check]

`--check` fails if any generated file is stale, which is what CI runs.

Generated files:

    core/crates/mav-analytic/src/model_zoo/registry.rs
    apps/ios/Maverick/Model/MavModelCatalog.swift
    apps/android/app/src/main/java/com/sennnen/mav/ml/MavModelCatalog.kt
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
MANIFEST = ROOT / "artifacts/models/manifest.json"
RUST = ROOT / "core/crates/mav-analytic/src/model_zoo/registry.rs"
SWIFT = ROOT / "apps/ios/Maverick/Model/MavModelCatalog.swift"
KOTLIN = ROOT / "apps/android/app/src/main/java/com/sennnen/mav/ml/MavModelCatalog.kt"
ML_DOC = ROOT / "docs/ml.md"

PARITY_MARKER = "<!-- PARITY-TABLE -->"
BUNDLE_MARKER = "<!-- BUNDLE-LINE -->"

# The order the parity table reads in: front-ends first, then the heads that consume them,
# then everything else. Alphabetical would separate `pulse_ppg` from `pulsenet_foundation`.
DOC_ORDER = [
    "pulse_ppg",
    "pulsenet_foundation",
    "halite_ppg_score",
    "halite_risk_tree",
    "sleepnet_moonstone",
    "sleepnet_bdi",
    "sleepnet_bdi_v3",
    "awhr_imputation",
    "dhrv_imputation",
    "activity_detection",
    "activity_transition",
    "energy_expenditure_hr",
    "illness_detection",
]

BANNER = "Generated by tools/ml/generate_bindings.py from artifacts/models/manifest.json. Do not edit."


def camel(slug: str) -> str:
    return "".join(part.capitalize() for part in slug.split("_"))


def dtype_rust(dtype: str) -> str:
    return "TensorDtype::Int32" if dtype in ("int32", "int64") else "TensorDtype::Float32"


def standing_rust(standing: str) -> str:
    return {
        "first_party": "ModelStanding::FirstParty",
        "open_licensed": "ModelStanding::OpenLicensed",
    }[standing]


def rust_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def version_tuple(version: str) -> str:
    parts = (version.split(".") + ["0", "0", "0"])[:3]
    return f"Version::new({int(parts[0])}, {int(parts[1])}, {int(parts[2])})"


def render_rust(models: list[dict]) -> str:
    lines: list[str] = []
    lines.append(f"//! {BANNER}")
    lines.append("//!")
    lines.append("//! One entry per admitted model. The shapes are the shapes the converted artefact")
    lines.append("//! was built at, and the hashes are the artefacts in the two app bundles, so a")
    lines.append("//! mismatch between this table and what ships is a build failure rather than a")
    lines.append("//! runtime surprise. Re-run the generator after any conversion.")
    lines.append("")
    lines.append("use super::{ModelContract, ModelStanding, TensorDtype, TensorSpec};")
    lines.append("use mav_model::version::Version;")
    lines.append("")
    lines.append("/// Every model this build ships, on both platforms.")
    lines.append("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]")
    lines.append("pub enum ModelId {")
    for model in models:
        role = model["role"] or model["algorithm_id"]
        lines.append(f"    /// {role}")
        lines.append(f"    {camel(model['model'])},")
    lines.append("}")
    lines.append("")
    lines.append("/// In manifest order, which is alphabetical by slug.")
    lines.append(f"pub const ALL_MODELS: &[ModelId; {len(models)}] = &[")
    for model in models:
        lines.append(f"    ModelId::{camel(model['model'])},")
    lines.append("];")
    lines.append("")

    for model in models:
        name = camel(model["model"]).upper()
        lines.append(f"const {name}_INPUTS: &[TensorSpec] = &[")
        for spec in model["inputs"]:
            shape = ", ".join(str(dimension) for dimension in spec["shape"])
            lines.append(
                f"    TensorSpec {{ name: {rust_string(spec['name'])}, "
                f"shape: &[{shape}], dtype: {dtype_rust(spec['dtype'])} }},"
            )
        lines.append("];")
        lines.append(f"const {name}_OUTPUTS: &[TensorSpec] = &[")
        for spec in model["outputs"]:
            shape = ", ".join(str(dimension) for dimension in spec["shape"])
            lines.append(
                f"    TensorSpec {{ name: {rust_string(spec['name'])}, "
                f"shape: &[{shape}], dtype: {dtype_rust(spec['dtype'])} }},"
            )
        lines.append("];")
        lines.append("")

    lines.append("impl ModelId {")
    lines.append("    /// The frozen contract for this model.")
    lines.append("    pub const fn contract(self) -> ModelContract {")
    lines.append("        match self {")
    for model in models:
        variant = camel(model["model"])
        name = variant.upper()
        lines.append(f"            Self::{variant} => ModelContract {{")
        lines.append(f"                id: Self::{variant},")
        lines.append(f"                slug: {rust_string(model['model'])},")
        lines.append(f"                algorithm_id: {rust_string(model['algorithm_id'])},")
        lines.append(f"                algorithm_version: {version_tuple(model['algorithm_version'])},")
        lines.append(f"                inputs: {name}_INPUTS,")
        lines.append(f"                outputs: {name}_OUTPUTS,")
        lines.append(f"                coreml_sha256: {rust_string(model['coreml']['sha256'])},")
        lines.append(f"                tflite_sha256: {rust_string(model['tflite']['sha256'])},")
        lines.append(f"                standing: {standing_rust(model['standing'])},")
        lines.append(f"                licence: {rust_string(model['licence'])},")
        lines.append(f"                role: {rust_string(model['role'])},")
        lines.append("            },")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    /// Resolve a model from the slug the platform layer uses as its artefact name.")
    lines.append("    pub fn from_slug(slug: &str) -> Option<Self> {")
    lines.append("        match slug {")
    for model in models:
        lines.append(f"            {rust_string(model['model'])} => Some(Self::{camel(model['model'])}),")
    lines.append("            _ => None,")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# The Core ML compute-unit name each admitted configuration maps to in Swift.
# Mirrors coreml_precision.FULL_WIDTH_DESCRIPTION. The one policy that computes nothing at
# half width, and therefore the one that must not be offered Android's accelerators either.
FULL_WIDTH_ARITHMETIC = "float16 weights, float32 arithmetic"

# Models the GPU delegate may not run at half width, decided on hardware.
ANDROID_DELEGATE = ROOT / "artifacts/models/android_delegate.json"


def android_paths():
    """Which execution path each model takes on Android, per the recorded device sweep.

    Absent the file every model runs on the CPU. That is the honest default rather than a
    conservative one: the CPU path is the only one measured accurate on every model in the
    zoo, and an accelerator admitted without a measurement behind it is exactly what the sweep
    was written to stop.
    """
    if not ANDROID_DELEGATE.exists():
        return {}
    return json.loads(ANDROID_DELEGATE.read_text()).get("paths", {})

SWIFT_COMPUTE_UNITS = {
    "ALL": "all",
    "CPU_AND_NE": "cpuAndNeuralEngine",
    "CPU_AND_GPU": "cpuAndGPU",
    "CPU_ONLY": "cpuOnly",
}


def render_swift(models: list[dict]) -> str:
    lines: list[str] = []
    lines.append(f"// {BANNER}")
    lines.append("")
    lines.append("import CoreML")
    lines.append("import Foundation")
    lines.append("")
    lines.append("/// The Core ML artefacts this build ships, and the tensor contract each one binds to.")
    lines.append("///")
    lines.append("/// `admittedSHA256` is the hash of the `model.mlmodel` inside the source `.mlpackage`.")
    lines.append("/// Xcode compiles that package to an `.mlmodelc`, so the running app cannot re-derive")
    lines.append("/// the hash; `tools/check_model_assets.py` proves the shipped package matches this")
    lines.append("/// value, and the runner reports it to core so an unadmitted build fails closed.")
    lines.append("enum MavModelCatalog {")
    lines.append("  struct TensorSpec {")
    lines.append("    let name: String")
    lines.append("    let shape: [Int]")
    lines.append("    var elementCount: Int { shape.reduce(1, *) }")
    lines.append("  }")
    lines.append("")
    lines.append("  /// Which compute units this model was admitted under.")
    lines.append("  ///")
    lines.append("  /// Not a performance hint. Core ML's backends do not agree with each other on")
    lines.append("  /// every graph: the sleep models are exact on the CPU and on the Neural Engine")
    lines.append("  /// and wrong by more than one whole relative unit on the GPU, at every")
    lines.append("  /// precision. Each model records the configuration its parity was measured")
    lines.append("  /// under, and the runner uses that one.")
    lines.append("  enum ComputeUnits: String {")
    lines.append("    case all")
    lines.append("    case cpuAndNeuralEngine")
    lines.append("    case cpuAndGPU")
    lines.append("    case cpuOnly")
    lines.append("")
    lines.append("    var mlComputeUnits: MLComputeUnits {")
    lines.append("      switch self {")
    lines.append("      case .all: .all")
    lines.append("      case .cpuAndNeuralEngine: .cpuAndNeuralEngine")
    lines.append("      case .cpuAndGPU: .cpuAndGPU")
    lines.append("      case .cpuOnly: .cpuOnly")
    lines.append("      }")
    lines.append("    }")
    lines.append("  }")
    lines.append("")
    lines.append("  struct Entry {")
    lines.append("    let slug: String")
    lines.append("    let admittedSHA256: String")
    lines.append("    let computeUnits: ComputeUnits")
    lines.append("    let inputs: [TensorSpec]")
    lines.append("    let outputs: [TensorSpec]")
    lines.append("  }")
    lines.append("")
    lines.append("  static let entries: [String: Entry] = [")
    for model in models:
        lines.append(f"    \"{model['model']}\": Entry(")
        lines.append(f"      slug: \"{model['model']}\",")
        lines.append(f"      admittedSHA256: \"{model['coreml']['sha256']}\",")
        lines.append(f"      computeUnits: .{SWIFT_COMPUTE_UNITS[model['coreml'].get('compute_units', 'ALL')]},")
        lines.append("      inputs: [")
        for spec in model["inputs"]:
            shape = ", ".join(str(dimension) for dimension in spec["shape"])
            lines.append(f"        TensorSpec(name: \"{spec['name']}\", shape: [{shape}]),")
        lines.append("      ],")
        lines.append("      outputs: [")
        for spec in model["outputs"]:
            shape = ", ".join(str(dimension) for dimension in spec["shape"])
            lines.append(f"        TensorSpec(name: \"{spec['name']}\", shape: [{shape}]),")
        lines.append("      ]")
        lines.append("    ),")
    lines.append("  ]")
    lines.append("")
    lines.append("  static let slugs: [String] = [")
    for model in models:
        lines.append(f"    \"{model['model']}\",")
    lines.append("  ]")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_kotlin(models: list[dict]) -> str:
    lines: list[str] = []
    lines.append(f"// {BANNER}")
    lines.append("")
    lines.append("package com.sennnen.mav.ml")
    lines.append("")
    lines.append("/**")
    lines.append(" * The TensorFlow Lite artefacts this build ships, and the tensor contract each binds to.")
    lines.append(" *")
    lines.append(" * `admittedSha256` is the hash of the asset as packaged. The runner hashes the mapped")
    lines.append(" * buffer at load and refuses a model whose bytes are not this value, so a swapped asset")
    lines.append(" * fails at open rather than producing an unattributable number.")
    lines.append(" *")
    lines.append(" * `acceleratesWell` carries the decision the Core ML conversion made by measurement:")
    lines.append(" * true where the model was admitted at half-precision arithmetic, false where it had to")
    lines.append(" * keep full width to stay near its reference. Android has no equivalent measurement at")
    lines.append(" * runtime, and every accelerator here is half-precision hardware, so the same answer")
    lines.append(" * decides whether MavModelAcceleration offers this model the GPU. That is what keeps")
    lines.append(" * the two platforms computing the same arithmetic from the same weights.")
    lines.append(" *")
    lines.append(" * `preferredPath` is where the model actually runs here, and unlike the flag above it")
    lines.append(" * was measured on hardware rather than inferred from iOS. The inference was wrong:")
    lines.append(" * \"float16\" is not one behaviour across platforms — Apple's Neural Engine accumulates")
    lines.append(" * a half-width matmul into a wider register and the GPU delegate does not — and the")
    lines.append(" * delegate also turned out slower than the CPU on all but one of these graphs. The CPU")
    lines.append(" * is therefore the default, and a model leaves it only where a sweep measured the GPU")
    lines.append(" * both faster and no less accurate. tools/ml/android_delegate.py writes the decision;")
    lines.append(" * artifacts/models/android_delegate.json records the measurements behind it.")
    lines.append(" */")
    # Internal because `preferredPath` names an internal type, and because nothing outside this
    # package should be reading the zoo's wiring: the app talks to MavModelBridge.
    lines.append("internal object MavModelCatalog {")
    lines.append("    data class TensorSpec(val name: String, val shape: IntArray) {")
    lines.append("        val elementCount: Int get() = shape.fold(1) { total, side -> total * side }")
    lines.append("")
    lines.append("        override fun equals(other: Any?): Boolean =")
    lines.append("            other is TensorSpec && name == other.name && shape.contentEquals(other.shape)")
    lines.append("")
    lines.append("        override fun hashCode(): Int = 31 * name.hashCode() + shape.contentHashCode()")
    lines.append("    }")
    lines.append("")
    lines.append("    data class Entry(")
    lines.append("        val slug: String,")
    lines.append("        val assetPath: String,")
    lines.append("        val admittedSha256: String,")
    lines.append("        val acceleratesWell: Boolean,")
    lines.append("        val preferredPath: MavModelAcceleration.Path,")
    lines.append("        val inputs: List<TensorSpec>,")
    lines.append("        val outputs: List<TensorSpec>,")
    lines.append("    )")
    lines.append("")
    lines.append("    val entries: Map<String, Entry> = mapOf(")
    paths = android_paths()
    for model in models:
        key = model["model"]
        lines.append(f'        "{key}" to Entry(')
        lines.append(f'            slug = "{key}",')
        lines.append(f'            assetPath = "models/{key}.tflite",')
        lines.append(f'            admittedSha256 = "{model["tflite"]["sha256"]}",')
        # Every policy except the full-width one computes at least partly at half width, so
        # a substring or equality test on the description gets the mixed policies backwards:
        # "float16, accumulations at float32" is a half-precision model.
        half = model["coreml"].get("precision", "") != FULL_WIDTH_ARITHMETIC
        lines.append(f'            acceleratesWell = {"true" if half else "false"},')
        path = paths.get(key, "CPU")
        lines.append(f"            preferredPath = MavModelAcceleration.Path.{path},")
        lines.append("            inputs = listOf(")
        for spec in model["inputs"]:
            shape = ", ".join(str(dimension) for dimension in spec["shape"])
            lines.append(f'                TensorSpec("{spec["name"]}", intArrayOf({shape})),')
        lines.append("            ),")
        lines.append("            outputs = listOf(")
        for spec in model["outputs"]:
            shape = ", ".join(str(dimension) for dimension in spec["shape"])
            lines.append(f'                TensorSpec("{spec["name"]}", intArrayOf({shape})),')
        lines.append("            ),")
        lines.append("        ),")
    lines.append("    )")
    lines.append("")
    lines.append("    val slugs: List<String> = entries.keys.toList()")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def rustfmt(text: str) -> str:
    """Format the Rust output the way `cargo fmt` would.

    Without this the generator and the repository's formatter disagree, and the staleness
    check fails on whitespace the moment anyone runs `cargo fmt`.
    """
    binary = shutil.which("rustfmt")
    if binary is None:
        return text
    result = subprocess.run(
        [binary, "--edition", "2021", "--emit", "stdout"],
        input=text,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return text
    # rustfmt --emit stdout prefixes the buffer name; strip it.
    lines = result.stdout.splitlines(keepends=True)
    if lines and lines[0].startswith("//"):
        return "".join(lines)
    return result.stdout


def render_parity_table(models: list[dict]) -> str:
    """The parity table in docs/ml.md, so prose numbers cannot drift from the manifest."""
    by_slug = {model["model"]: model for model in models}
    ordered = [by_slug[slug] for slug in DOC_ORDER if slug in by_slug]
    ordered += [m for m in models if m["model"] not in DOC_ORDER]
    lines = [
        "| Model | iOS bytes | Core ML rel. err | Android bytes | TFLite rel. err | Platforms agree to |",
        "|---|---|---|---|---|---|",
    ]
    for model in ordered:
        lines.append(
            "| `{}` | {:,} | {:.2e} | {:,} | {:.2e} | {:.2e} |".format(
                model["model"],
                model["coreml"]["bytes"],
                model["coreml"]["parity"]["max_rel"],
                model["tflite"]["bytes"],
                model["tflite"]["parity"]["max_rel"],
                model.get("cross_platform", {}).get("max_rel", float("nan")),
            )
        )
    return "\n".join(lines)


def render_bundle_line(manifest: dict) -> str:
    ios = manifest["bundle_bytes"]["ios"]
    android = manifest["bundle_bytes"]["android"]
    return (
        "Bundle cost: **{:.1f} MB on iOS, {:.1f} MB on Android**, across {} models.".format(
            ios / 1e6, android / 1e6, len(manifest["models"])
        )
    )


def render_ml_doc(manifest: dict) -> str:
    """Substitute the generated blocks into docs/ml.md between their markers."""
    text = ML_DOC.read_text()
    for marker, rendered in (
        (PARITY_MARKER, render_parity_table(manifest["models"])),
        (BUNDLE_MARKER, render_bundle_line(manifest)),
    ):
        start = text.index(marker)
        end = text.index(marker, start + len(marker))
        text = text[: start + len(marker)] + "\n\n" + rendered + "\n\n" + text[end:]
    return text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    manifest = json.loads(MANIFEST.read_text())
    models = manifest["models"]

    rendered = {
        RUST: rustfmt(render_rust(models)),
        SWIFT: render_swift(models),
        KOTLIN: render_kotlin(models),
        ML_DOC: render_ml_doc(manifest),
    }

    stale = []
    for path, text in rendered.items():
        current = path.read_text() if path.exists() else None
        if current != text:
            stale.append(path)
    if arguments.check:
        for path in stale:
            print(f"generate_bindings: {path.relative_to(ROOT)} is stale", file=sys.stderr)
        if stale:
            return 1
        print(f"generate_bindings: ok, {len(models)} models")
        return 0

    for path, text in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    print(f"generate_bindings: wrote {len(rendered)} files for {len(models)} models")
    return 0


if __name__ == "__main__":
    sys.exit(main())
