#!/usr/bin/env python3
"""Golden vectors for the popsicle front-end, generated by running the archive itself.

The eight popsicle models take two tensors — a four-column scalar block and a three-column daily
series — and both are assembled by a preprocessor that stayed in the training archive. Reading
that preprocessor's source says what it does; running it says what it *produces*, and only the
second catches a misread of the order the columns go in.

So this does not reimplement anything. It calls `popsicle_1_8_1.pt`'s own
`PassThroughPreprocessor` on inputs chosen to exercise the edges — values below the valid range,
above it, exactly on it, and NaN — and writes what comes back. The Rust port in
`mav_analytic::model_zoo::cycle` is then held to those numbers by
`tests::matches_the_archive_on_generated_vectors`, the same arrangement every deterministic port
in this repository already uses.

Usage
    popsicle_vectors.py            # writes artifacts/models/vectors/popsicle_1_8_1.json
    popsicle_vectors.py --check    # regenerate and compare, without writing
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
ARCHIVE = os.path.join(ROOT, "tools/decrypted_models/popsicle_1_8_1.pt")
OUT = os.path.join(ROOT, "artifacts/models/vectors/popsicle_1_8_1.json")

# The series columns, in the order the preprocessor emits them.
SERIES = ["highest_temperature", "average_breath_rate", "average_heart_rate"]
# The scalar columns the model takes, in order.
SCALARS = ["age", "typical_cycle_length", "typical_luteal_length", "cycle_day"]


def cases() -> list[dict]:
    """Inputs chosen to land on both sides of every documented bound.

    The valid ranges are `[35.5, 37.5]` for temperature, `[8, 24]` for breath rate and
    `[30, 120]` for heart rate. A case for each: inside, on each edge, outside each edge, and
    NaN — because "rejected" and "missing" have to end up in the same place and it is worth
    proving they do rather than assuming it.
    """
    return [
        {
            "name": "typical_cycle_all_inside_range",
            "age": 31.0,
            "typical_cycle_length": 29.0,
            "typical_luteal_length": 13.0,
            "series": [[36.2, 15.0, 58.0], [36.4, 15.5, 57.0], [36.9, 16.0, 60.0]],
        },
        {
            "name": "values_on_both_edges_of_every_range",
            "age": 35.0,
            "typical_cycle_length": 28.0,
            "typical_luteal_length": 13.0,
            "series": [[35.5, 8.0, 30.0], [37.5, 24.0, 120.0]],
        },
        {
            "name": "values_outside_every_range_are_rejected",
            "age": 35.0,
            "typical_cycle_length": 28.0,
            "typical_luteal_length": 13.0,
            "series": [[35.4, 7.9, 29.9], [37.6, 24.1, 120.1]],
        },
        {
            "name": "missing_days_and_rejected_days_agree",
            "age": 42.0,
            "typical_cycle_length": 31.0,
            "typical_luteal_length": 14.0,
            "series": [
                [math.nan, math.nan, math.nan],
                [36.6, 14.0, 55.0],
                [99.0, 99.0, 999.0],
            ],
        },
        {
            "name": "the_wearers_luteal_length_is_replaced_by_the_default",
            "age": 30.0,
            "typical_cycle_length": 28.0,
            "typical_luteal_length": 19.0,
            "series": [[36.5, 15.0, 60.0]],
        },
        {
            "name": "a_short_luteal_length_is_replaced_too",
            "age": 30.0,
            "typical_cycle_length": 28.0,
            "typical_luteal_length": 8.0,
            "series": [[36.5, 15.0, 60.0]],
        },
        {
            "name": "a_single_day_history",
            "age": 24.0,
            "typical_cycle_length": 26.0,
            "typical_luteal_length": 12.0,
            "series": [[36.8, 17.0, 62.0]],
        },
    ]


def run() -> dict:
    import torch

    model = torch.jit.load(ARCHIVE, map_location="cpu")
    preprocessor = model._preprocessor

    out = {
        "archive": "popsicle_1_8_1.pt",
        "note": (
            "Generated by tools/ml/popsicle_vectors.py from the archive's own "
            "PassThroughPreprocessor. Do not hand-edit; regenerate."
        ),
        "series_columns": SERIES,
        "scalar_columns": SCALARS,
        "cases": [],
    }

    for case in cases():
        days = len(case["series"])
        series = torch.tensor(case["series"], dtype=torch.float32).unsqueeze(0)
        one = lambda value: torch.tensor([float(value)], dtype=torch.float32)  # noqa: E731
        empty = torch.zeros(1, 0, dtype=torch.float32)
        produced = preprocessor.forward(
            one(0.0),  # complete_cycle
            one(case["age"]),
            one(case["typical_cycle_length"]),
            one(case["typical_luteal_length"]),
            empty,  # cycle_lengths
            empty,  # follicular_lengths
            one(0.0),  # hormones
            empty,  # positive_lh_test_days
            empty,  # exclusion_tags
            series[:, :, 0],
            series[:, :, 1],
            series[:, :, 2],
        )
        # NaN is not JSON. It appears both in the inputs (a day with no reading) and could in
        # the outputs, so both sides travel as null and the Rust test reads null as "missing".
        def jsonable(values):
            return [None if isinstance(v, float) and math.isnan(v) else v for v in values]

        record = {
            "name": case["name"],
            "days": days,
            "inputs": {
                **{k: v for k, v in case.items() if k != "series"},
                "series": [jsonable(row) for row in case["series"]],
            },
        }
        for key, value in produced.items():
            record[key] = jsonable(value.detach().cpu().flatten().tolist())
            record[f"{key}__shape"] = list(value.shape)
        out["cases"].append(record)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="compare without writing")
    args = parser.parse_args()

    if not os.path.isfile(ARCHIVE):
        print(f"archive is not available: {ARCHIVE}", file=sys.stderr)
        return 1

    produced = run()
    text = json.dumps(produced, indent=1, sort_keys=True, allow_nan=False) + "\n"
    if args.check:
        if not os.path.isfile(OUT):
            print(f"popsicle_vectors: {OUT} does not exist", file=sys.stderr)
            return 1
        with open(OUT) as handle:
            if handle.read() != text:
                print("popsicle_vectors: vectors differ from the archive", file=sys.stderr)
                return 1
        print("popsicle_vectors: ok")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as handle:
        handle.write(text)
    print(f"popsicle_vectors: wrote {len(produced['cases'])} cases to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
