[package]
name = "mav-engine"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mav-model = { workspace = true }
mav-connector-abi = { workspace = true }
mav-connector-runtime = { workspace = true }
mav-analytic = { workspace = true }
mav-feature = { workspace = true }
mav-obs = { workspace = true }
mav-sqi = { workspace = true }
mav-timeline = { workspace = true }
mav-store = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

[lints]
workspace = true
