package com.sennnen.mav.data

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.io.InputStream
import java.io.OutputStream
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.CipherInputStream
import javax.crypto.CipherOutputStream
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Optional encryption at rest for backup snapshots (ANDROID_PARITY_ROADMAP.md C4, phase 1).
 *
 * OFF by default and deliberately absent from onboarding — debug logs and CSV exports stay
 * plaintext so shared feedback remains readable (maintainer requirement). When the Settings
 * toggle is on, `.noopbak` snapshots are wrapped in a hardware-Keystore AES/GCM envelope:
 *
 *     "NOOPENC1" (8 bytes) · IV (12 bytes) · GCM ciphertext of the whole zip
 *
 * The key never leaves the device's Keystore, so an encrypted backup only restores on the
 * device that wrote it — that IS the at-rest contract; users who need portable backups leave
 * the toggle off. Restore auto-detects the envelope, so mixed folders (some encrypted, some
 * not) restore transparently.
 */
object AuraDataProtection {
    private const val PREFS = "noop_prefs"
    private const val KEY_ENABLED = "noop.encryptAtRest"

    private const val KEYSTORE = "AndroidKeyStore"
    private const val KEY_ALIAS = "noop.atrest.v1"
    private const val TRANSFORM = "AES/GCM/NoPadding"
    private const val TAG_BITS = 128
    private const val IV_LEN = 12

    /** The 8-byte envelope magic. Plain zips start "PK", plain SQLite "SQLite f" — no overlap. */
    val MAGIC: ByteArray = "NOOPENC1".toByteArray(Charsets.US_ASCII)

    fun enabled(context: Context): Boolean =
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE).getBoolean(KEY_ENABLED, false)

    fun setEnabled(context: Context, on: Boolean) {
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit().putBoolean(KEY_ENABLED, on).apply()
    }

    /** True when [header] (the first ≥8 bytes of a file) carries the envelope magic. */
    fun isEncrypted(header: ByteArray): Boolean {
        if (header.size < MAGIC.size) return false
        for (i in MAGIC.indices) if (header[i] != MAGIC[i]) return false
        return true
    }

    /**
     * Wrap [out] for writing: pass-through when the toggle is off; magic + IV + GCM stream
     * when on. The caller closes the returned stream (closing it closes [out]).
     */
    fun wrapOutput(context: Context, out: OutputStream): OutputStream {
        if (!enabled(context)) return out
        val cipher = Cipher.getInstance(TRANSFORM)
        cipher.init(Cipher.ENCRYPT_MODE, key())
        out.write(MAGIC)
        out.write(cipher.iv)   // GCM IV is generated by the Keystore, always IV_LEN bytes
        return CipherOutputStream(out, cipher)
    }

    /**
     * Decrypting view over [input], which must be positioned at byte 0 of an encrypted file.
     * Consumes the magic + IV, returns the plaintext stream. Throws on a bad envelope or a
     * missing key (e.g. the backup came from another device).
     */
    fun decryptingStream(input: InputStream): InputStream {
        val magic = ByteArray(MAGIC.size)
        readFully(input, magic)
        require(isEncrypted(magic)) { "Not an encrypted NOOP backup." }
        val iv = ByteArray(IV_LEN)
        readFully(input, iv)
        val cipher = Cipher.getInstance(TRANSFORM)
        cipher.init(Cipher.DECRYPT_MODE, key(), GCMParameterSpec(TAG_BITS, iv))
        return CipherInputStream(input, cipher)
    }

    private fun readFully(input: InputStream, buf: ByteArray) {
        var off = 0
        while (off < buf.size) {
            val n = input.read(buf, off, buf.size - off)
            require(n > 0) { "Truncated encrypted backup." }
            off += n
        }
    }

    private fun key(): SecretKey {
        val ks = KeyStore.getInstance(KEYSTORE).apply { load(null) }
        (ks.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        val gen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE)
        gen.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build(),
        )
        return gen.generateKey()
    }
}
