// Generated by tools/gen_design_tokens.py from tokens/aura.json. Do not edit.

import CoreGraphics

enum AuraTokens {
  // Colours: (dark, light) as RGB hex.
  static let bg: (dark: UInt32, light: UInt32) = (0x000000, 0xF5F4F1)
  static let card: (dark: UInt32, light: UInt32) = (0x141416, 0xEDECE8)
  static let cardEdge: (dark: UInt32, light: UInt32) = (0x0B0B0C, 0xF4F3F0)
  static let ink: (dark: UInt32, light: UInt32) = (0xFFFFFF, 0x0C0C0D)
  static let accentInk: (dark: UInt32, light: UInt32) = (0xE7FE55, 0x74731A)
  static let good: (dark: UInt32, light: UInt32) = (0x3DE383, 0x1F9E57)
  static let fair: (dark: UInt32, light: UInt32) = (0xF5B840, 0xC4841A)
  static let bad: (dark: UInt32, light: UInt32) = (0xFF5A66, 0xD83A44)

  // Colours identical in both schemes.
  static let accent: UInt32 = 0xE7FE55

  // Colours carrying an alpha per scheme.
  static let hairline: (dark: (UInt32, CGFloat), light: (UInt32, CGFloat)) = ((0xFFFFFF, 0.08), (0x0C0C0D, 0.1))
  static let scrim: (dark: (UInt32, CGFloat), light: (UInt32, CGFloat)) = ((0x000000, 0.28), (0xFFFFFF, 0.6))
  static let grid: (dark: (UInt32, CGFloat), light: (UInt32, CGFloat)) = ((0xFFFFFF, 0.07), (0x0C0C0D, 0.08))

  // Metric family hues: glow centre and the edge it blooms out of.
  static let chargeGlow: (dark: UInt32, light: UInt32) = (0x14C078, 0x6FD3A2)
  static let chargeEdge: (dark: UInt32, light: UInt32) = (0x05241A, 0xDDF0E6)
  static let restGlow: (dark: UInt32, light: UInt32) = (0x3E7BFF, 0x8FB2FB)
  static let restEdge: (dark: UInt32, light: UInt32) = (0x061634, 0xE2EAFC)
  static let effortGlow: (dark: UInt32, light: UInt32) = (0xF52E9C, 0xFB7EC2)
  static let effortEdge: (dark: UInt32, light: UInt32) = (0x2A0A1E, 0xFCE2F0)
  static let heartGlow: (dark: UInt32, light: UInt32) = (0xF5476A, 0xFB8194)
  static let heartEdge: (dark: UInt32, light: UInt32) = (0x2A0912, 0xFCE4E8)
  static let energyGlow: (dark: UInt32, light: UInt32) = (0xE0A81E, 0xF3CE5A)
  static let energyEdge: (dark: UInt32, light: UInt32) = (0x241C06, 0xFAF0D8)
  static let vitalsGlow: (dark: UInt32, light: UInt32) = (0x12AEBE, 0x76D3DF)
  static let vitalsEdge: (dark: UInt32, light: UInt32) = (0x042426, 0xDFF3F6)

  // spacing
  static let screenMargin: CGFloat = 20
  static let cardSpacing: CGFloat = 12
  static let sectionGap: CGFloat = 24
  static let tilePadding: CGFloat = 20

  // radii
  static let cardRadius: CGFloat = 32
  static let tileRadius: CGFloat = 28

  // typeScale
  static let title: CGFloat = 19
  static let label: CGFloat = 15
  static let sub: CGFloat = 14
  static let caption: CGFloat = 12

}
