// Generated by tools/gen_design_tokens.py from tokens/aura.json. Do not edit.

package com.sennnen.mav.ui.aura

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object AuraTokens {
    // Colours: RGB hex, resolved per scheme by the palette.
    const val bgDark: Long = 0x070B0B
    const val bgLight: Long = 0xE7EDED
    const val cardDark: Long = 0x101617
    const val cardLight: Long = 0xFFFFFF
    const val cardEdgeDark: Long = 0x182021
    const val cardEdgeLight: Long = 0xF3F7F7
    const val sunkenDark: Long = 0x040707
    const val sunkenLight: Long = 0xDAE3E3
    const val inkDark: Long = 0xE4EDED
    const val inkLight: Long = 0x0E1516
    const val accentInkDark: Long = 0x7BAEA8
    const val accentInkLight: Long = 0x2F5B56
    const val goodDark: Long = 0x7BAEA8
    const val goodLight: Long = 0x2F5B56
    const val badDark: Long = 0xE08585
    const val badLight: Long = 0xA83232
    const val focusDark: Long = 0xE4EDED
    const val focusLight: Long = 0x16211F

    // Colours carrying an alpha per scheme.
    const val hairlineDark: Long = 0xE4EDED
    const val hairlineDarkAlpha: Float = 0.16f
    const val hairlineLight: Long = 0x0E1516
    const val hairlineLightAlpha: Float = 0.15f
    const val hairlineStrongDark: Long = 0xE4EDED
    const val hairlineStrongDarkAlpha: Float = 0.28f
    const val hairlineStrongLight: Long = 0x0E1516
    const val hairlineStrongLightAlpha: Float = 0.22f
    const val inkSecondaryDark: Long = 0xE4EDED
    const val inkSecondaryDarkAlpha: Float = 0.76f
    const val inkSecondaryLight: Long = 0x0E1516
    const val inkSecondaryLightAlpha: Float = 0.72f
    const val glassDark: Long = 0xE4EDED
    const val glassDarkAlpha: Float = 0.1f
    const val glassLight: Long = 0xFAFCFC
    const val glassLightAlpha: Float = 0.76f
    const val glassLineDark: Long = 0xE4EDED
    const val glassLineDarkAlpha: Float = 0.22f
    const val glassLineLight: Long = 0x0E1516
    const val glassLineLightAlpha: Float = 0.14f
    const val scrimDark: Long = 0x000000
    const val scrimDarkAlpha: Float = 0.58f
    const val scrimLight: Long = 0x0E1516
    const val scrimLightAlpha: Float = 0.3f
    const val photoScrimDark: Long = 0x0F3733
    const val photoScrimDarkAlpha: Float = 0.72f
    const val photoScrimLight: Long = 0x0F3733
    const val photoScrimLightAlpha: Float = 0.68f
    const val photoVeilDark: Long = 0x081413
    const val photoVeilDarkAlpha: Float = 0.85f
    const val photoVeilLight: Long = 0xDEEBE9
    const val photoVeilLightAlpha: Float = 0.87f
    const val bloomTopDark: Long = 0x7BAEA8
    const val bloomTopDarkAlpha: Float = 0.18f
    const val bloomTopLight: Long = 0x5FB3A8
    const val bloomTopLightAlpha: Float = 0.3f
    const val bloomBottomDark: Long = 0x7BAEA8
    const val bloomBottomDarkAlpha: Float = 0.1f
    const val bloomBottomLight: Long = 0x5FB3A8
    const val bloomBottomLightAlpha: Float = 0.17f
    const val gridDark: Long = 0xE4EDED
    const val gridDarkAlpha: Float = 0.12f
    const val gridLight: Long = 0x0E1516
    const val gridLightAlpha: Float = 0.1f
    const val tintChargeDark: Long = 0x7BAEA8
    const val tintChargeDarkAlpha: Float = 0.16f
    const val tintChargeLight: Long = 0x2F5B56
    const val tintChargeLightAlpha: Float = 0.115f
    const val tintRestDark: Long = 0x7BAEA8
    const val tintRestDarkAlpha: Float = 0.135f
    const val tintRestLight: Long = 0x2F5B56
    const val tintRestLightAlpha: Float = 0.098f
    const val tintEffortDark: Long = 0x7BAEA8
    const val tintEffortDarkAlpha: Float = 0.112f
    const val tintEffortLight: Long = 0x2F5B56
    const val tintEffortLightAlpha: Float = 0.082f
    const val tintHeartDark: Long = 0x7BAEA8
    const val tintHeartDarkAlpha: Float = 0.09f
    const val tintHeartLight: Long = 0x2F5B56
    const val tintHeartLightAlpha: Float = 0.066f
    const val tintEnergyDark: Long = 0x7BAEA8
    const val tintEnergyDarkAlpha: Float = 0.07f
    const val tintEnergyLight: Long = 0x2F5B56
    const val tintEnergyLightAlpha: Float = 0.052f
    const val tintVitalsDark: Long = 0x7BAEA8
    const val tintVitalsDarkAlpha: Float = 0.052f
    const val tintVitalsLight: Long = 0x2F5B56
    const val tintVitalsLightAlpha: Float = 0.038f
    const val tintCycleDark: Long = 0x7BAEA8
    const val tintCycleDarkAlpha: Float = 0.036f
    const val tintCycleLight: Long = 0x2F5B56
    const val tintCycleLightAlpha: Float = 0.026f
    const val tintNeutralDark: Long = 0xE4EDED
    const val tintNeutralDarkAlpha: Float = 0.04f
    const val tintNeutralLight: Long = 0x0E1516
    const val tintNeutralLightAlpha: Float = 0.035f

    // Semantic metric families; every value resolves to the monochrome ink/wash.
    const val chargeGlowDark: Long = 0x8FD6CE
    const val chargeGlowLight: Long = 0x2E7F76
    const val chargeEdgeDark: Long = 0x16211F
    const val chargeEdgeLight: Long = 0xDDE9E7
    const val restGlowDark: Long = 0x7BCEC5
    const val restGlowLight: Long = 0x2B776F
    const val restEdgeDark: Long = 0x141F1E
    const val restEdgeLight: Long = 0xDDE9E7
    const val effortGlowDark: Long = 0x66C5BB
    const val effortGlowLight: Long = 0x286F67
    const val effortEdgeDark: Long = 0x121D1C
    const val effortEdgeLight: Long = 0xDDE9E7
    const val heartGlowDark: Long = 0x52BDB2
    const val heartGlowLight: Long = 0x256760
    const val heartEdgeDark: Long = 0x111B1A
    const val heartEdgeLight: Long = 0xDDE9E7
    const val energyGlowDark: Long = 0x47ADA3
    const val energyGlowLight: Long = 0x225F58
    const val energyEdgeDark: Long = 0x0F1918
    const val energyEdgeLight: Long = 0xDDE9E7
    const val vitalsGlowDark: Long = 0x409C93
    const val vitalsGlowLight: Long = 0x1F5751
    const val vitalsEdgeDark: Long = 0x0E1716
    const val vitalsEdgeLight: Long = 0xDDE9E7
    const val cycleGlowDark: Long = 0x398B83
    const val cycleGlowLight: Long = 0x1C4F4A
    const val cycleEdgeDark: Long = 0x0D1514
    const val cycleEdgeLight: Long = 0xDDE9E7

    // spacing
    val screenMargin: Dp = 20.dp
    val cardSpacing: Dp = 12.dp
    val sectionGap: Dp = 40.dp
    val tilePadding: Dp = 18.dp
    val railGap: Dp = 8.dp

    // radii
    val cardRadius: Dp = 24.dp
    val tileRadius: Dp = 20.dp
    val pillRadius: Dp = 16.dp
    val chipRadius: Dp = 12.dp

    // type scale
    val displayLargeSize: TextUnit = 34.sp
    val displaySize: TextUnit = 29.sp
    val numeralXLSize: TextUnit = 54.sp
    val numeralLargeSize: TextUnit = 42.sp
    val numeralMediumSize: TextUnit = 24.sp
    val numeralSmallSize: TextUnit = 19.sp
    val titleSize: TextUnit = 22.sp
    val labelSize: TextUnit = 15.sp
    val bodySize: TextUnit = 14.sp
    val subSize: TextUnit = 13.sp
    val captionSize: TextUnit = 11.sp
    val eyebrowSize: TextUnit = 10.sp
}
