// Generated by tools/gen_design_tokens.py from tokens/aura.json. Do not edit.

package com.sennnen.mav.ui.aura

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object AuraTokens {
    // Colours: RGB hex, resolved per scheme by the palette.
    const val bgDark: Long = 0x000000
    const val bgLight: Long = 0xF5F4F1
    const val cardDark: Long = 0x141416
    const val cardLight: Long = 0xEDECE8
    const val cardEdgeDark: Long = 0x0B0B0C
    const val cardEdgeLight: Long = 0xF4F3F0
    const val inkDark: Long = 0xFFFFFF
    const val inkLight: Long = 0x0C0C0D
    const val accentInkDark: Long = 0xE7FE55
    const val accentInkLight: Long = 0x74731A
    const val goodDark: Long = 0x3DE383
    const val goodLight: Long = 0x1F9E57
    const val fairDark: Long = 0xF5B840
    const val fairLight: Long = 0xC4841A
    const val badDark: Long = 0xFF5A66
    const val badLight: Long = 0xD83A44

    // Colours identical in both schemes.
    const val accent: Long = 0xE7FE55

    // Colours carrying an alpha per scheme.
    const val hairlineDark: Long = 0xFFFFFF
    const val hairlineDarkAlpha: Float = 0.08f
    const val hairlineLight: Long = 0x0C0C0D
    const val hairlineLightAlpha: Float = 0.1f
    const val scrimDark: Long = 0x000000
    const val scrimDarkAlpha: Float = 0.28f
    const val scrimLight: Long = 0xFFFFFF
    const val scrimLightAlpha: Float = 0.6f
    const val gridDark: Long = 0xFFFFFF
    const val gridDarkAlpha: Float = 0.07f
    const val gridLight: Long = 0x0C0C0D
    const val gridLightAlpha: Float = 0.08f

    // Metric family hues: glow centre and the edge it blooms out of.
    const val chargeGlowDark: Long = 0x14C078
    const val chargeGlowLight: Long = 0x6FD3A2
    const val chargeEdgeDark: Long = 0x05241A
    const val chargeEdgeLight: Long = 0xDDF0E6
    const val restGlowDark: Long = 0x3E7BFF
    const val restGlowLight: Long = 0x8FB2FB
    const val restEdgeDark: Long = 0x061634
    const val restEdgeLight: Long = 0xE2EAFC
    const val effortGlowDark: Long = 0xF52E9C
    const val effortGlowLight: Long = 0xFB7EC2
    const val effortEdgeDark: Long = 0x2A0A1E
    const val effortEdgeLight: Long = 0xFCE2F0
    const val heartGlowDark: Long = 0xF5476A
    const val heartGlowLight: Long = 0xFB8194
    const val heartEdgeDark: Long = 0x2A0912
    const val heartEdgeLight: Long = 0xFCE4E8
    const val energyGlowDark: Long = 0xE0A81E
    const val energyGlowLight: Long = 0xF3CE5A
    const val energyEdgeDark: Long = 0x241C06
    const val energyEdgeLight: Long = 0xFAF0D8
    const val vitalsGlowDark: Long = 0x12AEBE
    const val vitalsGlowLight: Long = 0x76D3DF
    const val vitalsEdgeDark: Long = 0x042426
    const val vitalsEdgeLight: Long = 0xDFF3F6

    // spacing
    val screenMargin: Dp = 20.dp
    val cardSpacing: Dp = 12.dp
    val sectionGap: Dp = 24.dp
    val tilePadding: Dp = 20.dp

    // radii
    val cardRadius: Dp = 32.dp
    val tileRadius: Dp = 28.dp

    // type scale
    val titleSize: TextUnit = 19.sp
    val labelSize: TextUnit = 15.sp
    val subSize: TextUnit = 14.sp
    val captionSize: TextUnit = 12.sp
}
