//! Generated by tools/ml/generate_bindings.py from artifacts/models/manifest.json. Do not edit.
//!
//! One entry per admitted model. The shapes are the shapes the converted artefact
//! was built at, and the hashes are the artefacts in the two app bundles, so a
//! mismatch between this table and what ships is a build failure rather than a
//! runtime surprise. Re-run the generator after any conversion.

use super::{ModelContract, ModelStanding, TensorDtype, TensorSpec};
use mav_model::version::Version;

/// Every model this build ships, on both platforms.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ModelId {
    /// Embeds 85 context features per segment into a 312-d space
    ActivityContextEmbedding,
    /// Activity classification over 64 candidate segments of 77 features
    ActivityDetection,
    /// Combines the primary and secondary segment heads into the final per-segment output
    ActivityEnsemble,
    /// Self-attention over sixteen history segments; also returns its attention map
    ActivityHistoryTransformer,
    /// Primary per-segment activity head
    ActivityPrimarySegments,
    /// Secondary per-segment activity head, over the history encoder's output
    ActivitySecondarySegments,
    /// Activity-transition segmentation over a 64-minute window
    ActivityTransition,
    /// Bidirectional LSTM imputing awake heart rate over a 60-step context window
    AwhrImputation,
    /// Per-step activity features behind the awake-HR profile choice
    AwhrProfileCore,
    /// Three-way profile head over the recurrent layer's output
    AwhrProfileHead,
    /// Bidirectional recurrent layer between the profile features and the profile head
    AwhrProfileRecurrent,
    /// Embeds sixteen behaviour ids into the activity model's 256-d space
    BehaviorEmbedding,
    /// PPG transformer encoder: 1,024 normalised pulse samples to a 128-d embedding
    CvaEncoder,
    /// Previous-generation CNN cardiovascular-age network over pulse, VPG and APG
    CvaPredictorV1Base,
    /// The female branch of the CVA probe head
    CvaProbesFemale,
    /// Cardiovascular age, pulse-wave velocity and blood pressure from a CVA embedding
    CvaProbesMale,
    /// Daytime HRV imputation from temperature, MET, HR and their baselines
    DhrvImputation,
    /// Active energy expenditure for a window where heart rate is available
    EnergyExpenditureHr,
    /// Active energy expenditure for a window with no usable heart rate
    EnergyExpenditureNoHr,
    /// Scores one PulseNet embedding into the hypertension-risk PPG score
    HalitePpgScore,
    /// Gradient-boosted head over user info, baselines and the aggregated PPG score
    HaliteRiskTree,
    /// Illness likelihood from thirty days of eight daily biometric deviations
    IllnessDetection,
    /// Predicts the shortest plausible follicular phase for this wearer
    PopsicleMinFollicular,
    /// The previous generation of the follicular-length head
    PopsicleMinFollicularV16,
    /// Ovulation detection over up to forty cycle days of temperature, heart rate and breath rate
    PopsicleOvulationDetection,
    /// The previous generation of the ovulation detector
    PopsicleOvulationDetectionV16,
    /// Days until the next ovulation, per cycle day
    PopsicleOvulationPrediction,
    /// The previous generation of the ovulation predictor
    PopsicleOvulationPredictionV16,
    /// Days until the next period, per cycle day
    PopsiclePeriodPrediction,
    /// The previous generation of the period predictor
    PopsiclePeriodPredictionV16,
    /// Open-weight PPG foundation encoder: 240 s at 50 Hz to a 512-d embedding, pre-trained on uncurated field PPG
    PulsePpg,
    /// PPG foundation encoder: 30 s of detrended PPG at 50 Hz to a 256-d embedding
    PulsenetFoundation,
    /// Sleep stages and apnea events from interbeat intervals alone
    SleepnetBdi,
    /// Previous-generation interbeat-interval sleep-staging network
    SleepnetBdiV3,
    /// Sleep stages, apnea and SpO2 events over a 15-hour night
    SleepnetMoonstone,
    /// Embeds each segment's provenance — how the activity was recorded — into eight values
    SourceEmbedding,
    /// Step-eligibility features from one step-motion vector
    StepEligibility,
    /// Turns the eligibility features into one eligibility score
    StepHead,
    /// Parameterised sigmoid scaling the raw step count by eligibility
    StepMultiplier,
    /// U-Net over the workout PPG spectrogram window
    WhrUnetEncoder,
    /// Recurrent head turning U-Net features into a per-column heart rate
    WhrUnetHead,
}

/// In manifest order, which is alphabetical by slug.
pub const ALL_MODELS: &[ModelId; 41] = &[
    ModelId::ActivityContextEmbedding,
    ModelId::ActivityDetection,
    ModelId::ActivityEnsemble,
    ModelId::ActivityHistoryTransformer,
    ModelId::ActivityPrimarySegments,
    ModelId::ActivitySecondarySegments,
    ModelId::ActivityTransition,
    ModelId::AwhrImputation,
    ModelId::AwhrProfileCore,
    ModelId::AwhrProfileHead,
    ModelId::AwhrProfileRecurrent,
    ModelId::BehaviorEmbedding,
    ModelId::CvaEncoder,
    ModelId::CvaPredictorV1Base,
    ModelId::CvaProbesFemale,
    ModelId::CvaProbesMale,
    ModelId::DhrvImputation,
    ModelId::EnergyExpenditureHr,
    ModelId::EnergyExpenditureNoHr,
    ModelId::HalitePpgScore,
    ModelId::HaliteRiskTree,
    ModelId::IllnessDetection,
    ModelId::PopsicleMinFollicular,
    ModelId::PopsicleMinFollicularV16,
    ModelId::PopsicleOvulationDetection,
    ModelId::PopsicleOvulationDetectionV16,
    ModelId::PopsicleOvulationPrediction,
    ModelId::PopsicleOvulationPredictionV16,
    ModelId::PopsiclePeriodPrediction,
    ModelId::PopsiclePeriodPredictionV16,
    ModelId::PulsePpg,
    ModelId::PulsenetFoundation,
    ModelId::SleepnetBdi,
    ModelId::SleepnetBdiV3,
    ModelId::SleepnetMoonstone,
    ModelId::SourceEmbedding,
    ModelId::StepEligibility,
    ModelId::StepHead,
    ModelId::StepMultiplier,
    ModelId::WhrUnetEncoder,
    ModelId::WhrUnetHead,
];

const ACTIVITYCONTEXTEMBEDDING_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "context",
    shape: &[1, 16, 85],
    dtype: TensorDtype::Float32,
}];
const ACTIVITYCONTEXTEMBEDDING_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "embeddings",
    shape: &[1, 16, 312],
    dtype: TensorDtype::Float32,
}];

const ACTIVITYDETECTION_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[1, 64, 77],
    dtype: TensorDtype::Float32,
}];
const ACTIVITYDETECTION_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "activity_output",
    shape: &[1, 64, 262],
    dtype: TensorDtype::Float32,
}];

const ACTIVITYENSEMBLE_INPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "primary",
        shape: &[1, 16, 260],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "secondary",
        shape: &[1, 16, 260],
        dtype: TensorDtype::Float32,
    },
];
const ACTIVITYENSEMBLE_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "segment_output",
    shape: &[1, 16, 260],
    dtype: TensorDtype::Float32,
}];

const ACTIVITYHISTORYTRANSFORMER_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "segments",
    shape: &[1, 16, 573],
    dtype: TensorDtype::Float32,
}];
const ACTIVITYHISTORYTRANSFORMER_OUTPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "encoded",
        shape: &[1, 16, 336],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "attention",
        shape: &[1, 1, 6, 16, 18],
        dtype: TensorDtype::Float32,
    },
];

const ACTIVITYPRIMARYSEGMENTS_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[1, 16, 110],
    dtype: TensorDtype::Float32,
}];
const ACTIVITYPRIMARYSEGMENTS_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "segment_output",
    shape: &[1, 16, 260],
    dtype: TensorDtype::Float32,
}];

const ACTIVITYSECONDARYSEGMENTS_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[1, 16, 336],
    dtype: TensorDtype::Float32,
}];
const ACTIVITYSECONDARYSEGMENTS_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "segment_output",
    shape: &[1, 16, 260],
    dtype: TensorDtype::Float32,
}];

const ACTIVITYTRANSITION_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[1, 64, 29],
    dtype: TensorDtype::Float32,
}];
const ACTIVITYTRANSITION_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "transition_logits",
    shape: &[1, 64],
    dtype: TensorDtype::Float32,
}];

const AWHRIMPUTATION_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "window",
    shape: &[1, 60, 13],
    dtype: TensorDtype::Float32,
}];
const AWHRIMPUTATION_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "imputed_hr",
    shape: &[1, 60, 1],
    dtype: TensorDtype::Float32,
}];

const AWHRPROFILECORE_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[60, 19],
    dtype: TensorDtype::Float32,
}];
const AWHRPROFILECORE_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "profile_features",
    shape: &[60, 6],
    dtype: TensorDtype::Float32,
}];

const AWHRPROFILEHEAD_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[60, 32],
    dtype: TensorDtype::Float32,
}];
const AWHRPROFILEHEAD_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "profile_logits",
    shape: &[60, 3],
    dtype: TensorDtype::Float32,
}];

const AWHRPROFILERECURRENT_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[1, 60, 6],
    dtype: TensorDtype::Float32,
}];
const AWHRPROFILERECURRENT_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "encoded",
    shape: &[1, 60, 32],
    dtype: TensorDtype::Float32,
}];

const BEHAVIOREMBEDDING_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "behavior_ids",
    shape: &[1, 16],
    dtype: TensorDtype::Int32,
}];
const BEHAVIOREMBEDDING_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "embeddings",
    shape: &[1, 16, 256],
    dtype: TensorDtype::Float32,
}];

const CVAENCODER_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "pulses",
    shape: &[1, 1024],
    dtype: TensorDtype::Float32,
}];
const CVAENCODER_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "embeddings",
    shape: &[1, 128],
    dtype: TensorDtype::Float32,
}];

const CVAPREDICTORV1BASE_INPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "pulse_triple",
        shape: &[1, 3, 256],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "exogenous",
        shape: &[1, 8],
        dtype: TensorDtype::Float32,
    },
];
const CVAPREDICTORV1BASE_OUTPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "cva",
        shape: &[1, 1],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "pwv",
        shape: &[1, 1],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "features",
        shape: &[1, 272],
        dtype: TensorDtype::Float32,
    },
];

const CVAPROBESFEMALE_INPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "embeddings",
        shape: &[1, 128],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "age",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "weight",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "bmi",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
];
const CVAPROBESFEMALE_OUTPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "cva",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "pwv",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "systolic",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "diastolic",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
];

const CVAPROBESMALE_INPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "embeddings",
        shape: &[1, 128],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "age",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "weight",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "bmi",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
];
const CVAPROBESMALE_OUTPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "cva",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "pwv",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "systolic",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "diastolic",
        shape: &[1],
        dtype: TensorDtype::Float32,
    },
];

const DHRVIMPUTATION_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[1, 10],
    dtype: TensorDtype::Float32,
}];
const DHRVIMPUTATION_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "imputed_dhrv",
    shape: &[1, 1],
    dtype: TensorDtype::Float32,
}];

const ENERGYEXPENDITUREHR_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[1, 50],
    dtype: TensorDtype::Float32,
}];
const ENERGYEXPENDITUREHR_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "energy",
    shape: &[1, 1],
    dtype: TensorDtype::Float32,
}];

const ENERGYEXPENDITURENOHR_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[1, 42],
    dtype: TensorDtype::Float32,
}];
const ENERGYEXPENDITURENOHR_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "energy",
    shape: &[1, 1],
    dtype: TensorDtype::Float32,
}];

const HALITEPPGSCORE_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "embeddings",
    shape: &[1, 256],
    dtype: TensorDtype::Float32,
}];
const HALITEPPGSCORE_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "ppg_score",
    shape: &[1, 1],
    dtype: TensorDtype::Float32,
}];

const HALITERISKTREE_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[1, 13],
    dtype: TensorDtype::Float32,
}];
const HALITERISKTREE_OUTPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "label",
        shape: &[1],
        dtype: TensorDtype::Int32,
    },
    TensorSpec {
        name: "probabilities",
        shape: &[1, 2],
        dtype: TensorDtype::Float32,
    },
];

const ILLNESSDETECTION_INPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "scalars",
        shape: &[1, 4],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "time_series",
        shape: &[1, 8, 30],
        dtype: TensorDtype::Float32,
    },
];
const ILLNESSDETECTION_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "illness_probability",
    shape: &[1, 1],
    dtype: TensorDtype::Float32,
}];

const POPSICLEMINFOLLICULAR_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[1, 9],
    dtype: TensorDtype::Float32,
}];
const POPSICLEMINFOLLICULAR_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "min_follicular_days",
    shape: &[1, 1],
    dtype: TensorDtype::Float32,
}];

const POPSICLEMINFOLLICULARV16_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[1, 9],
    dtype: TensorDtype::Float32,
}];
const POPSICLEMINFOLLICULARV16_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "min_follicular_days",
    shape: &[1, 1],
    dtype: TensorDtype::Float32,
}];

const POPSICLEOVULATIONDETECTION_INPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "time_series",
        shape: &[1, 40, 3],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "scalars",
        shape: &[1, 40, 4],
        dtype: TensorDtype::Float32,
    },
];
const POPSICLEOVULATIONDETECTION_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "ovulation_probability",
    shape: &[1, 40, 1],
    dtype: TensorDtype::Float32,
}];

const POPSICLEOVULATIONDETECTIONV16_INPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "time_series",
        shape: &[1, 40, 3],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "scalars",
        shape: &[1, 40, 4],
        dtype: TensorDtype::Float32,
    },
];
const POPSICLEOVULATIONDETECTIONV16_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "ovulation_probability",
    shape: &[1, 40, 1],
    dtype: TensorDtype::Float32,
}];

const POPSICLEOVULATIONPREDICTION_INPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "time_series",
        shape: &[1, 40, 3],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "scalars",
        shape: &[1, 40, 4],
        dtype: TensorDtype::Float32,
    },
];
const POPSICLEOVULATIONPREDICTION_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "days",
    shape: &[1, 40, 1],
    dtype: TensorDtype::Float32,
}];

const POPSICLEOVULATIONPREDICTIONV16_INPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "time_series",
        shape: &[1, 40, 3],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "scalars",
        shape: &[1, 40, 4],
        dtype: TensorDtype::Float32,
    },
];
const POPSICLEOVULATIONPREDICTIONV16_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "days",
    shape: &[1, 40, 1],
    dtype: TensorDtype::Float32,
}];

const POPSICLEPERIODPREDICTION_INPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "time_series",
        shape: &[1, 40, 3],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "scalars",
        shape: &[1, 40, 4],
        dtype: TensorDtype::Float32,
    },
];
const POPSICLEPERIODPREDICTION_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "days",
    shape: &[1, 40, 1],
    dtype: TensorDtype::Float32,
}];

const POPSICLEPERIODPREDICTIONV16_INPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "time_series",
        shape: &[1, 40, 3],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "scalars",
        shape: &[1, 40, 4],
        dtype: TensorDtype::Float32,
    },
];
const POPSICLEPERIODPREDICTIONV16_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "days",
    shape: &[1, 40, 1],
    dtype: TensorDtype::Float32,
}];

const PULSEPPG_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "ppg",
    shape: &[1, 1, 12000],
    dtype: TensorDtype::Float32,
}];
const PULSEPPG_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "embeddings",
    shape: &[1, 512],
    dtype: TensorDtype::Float32,
}];

const PULSENETFOUNDATION_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "ppg",
    shape: &[1, 1, 1500],
    dtype: TensorDtype::Float32,
}];
const PULSENETFOUNDATION_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "embeddings",
    shape: &[1, 256],
    dtype: TensorDtype::Float32,
}];

const SLEEPNETBDI_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "high_res",
    shape: &[1, 115200, 2],
    dtype: TensorDtype::Float32,
}];
const SLEEPNETBDI_OUTPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "staging_logits",
        shape: &[1, 4, 1800],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "apnea_logits",
        shape: &[1, 1, 1800],
        dtype: TensorDtype::Float32,
    },
];

const SLEEPNETBDIV3_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "high_res",
    shape: &[1, 115200, 2],
    dtype: TensorDtype::Float32,
}];
const SLEEPNETBDIV3_OUTPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "staging_logits",
        shape: &[1, 4, 1800],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "apnea_logits",
        shape: &[1, 1, 1800],
        dtype: TensorDtype::Float32,
    },
];

const SLEEPNETMOONSTONE_INPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "high_res",
        shape: &[1, 115200, 3],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "low_res",
        shape: &[1, 1800, 1],
        dtype: TensorDtype::Float32,
    },
];
const SLEEPNETMOONSTONE_OUTPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "staging_logits",
        shape: &[1, 4, 1800],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "apnea_logits",
        shape: &[1, 1, 1800],
        dtype: TensorDtype::Float32,
    },
];

const SOURCEEMBEDDING_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "source_ids",
    shape: &[1, 16],
    dtype: TensorDtype::Int32,
}];
const SOURCEEMBEDDING_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "source_features",
    shape: &[1, 16, 8],
    dtype: TensorDtype::Float32,
}];

const STEPELIGIBILITY_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "motion",
    shape: &[1, 19],
    dtype: TensorDtype::Float32,
}];
const STEPELIGIBILITY_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "eligibility_features",
    shape: &[1, 4],
    dtype: TensorDtype::Float32,
}];

const STEPHEAD_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "eligibility_features",
    shape: &[1, 4],
    dtype: TensorDtype::Float32,
}];
const STEPHEAD_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "eligibility",
    shape: &[1, 1],
    dtype: TensorDtype::Float32,
}];

const STEPMULTIPLIER_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "eligibility",
    shape: &[1, 1],
    dtype: TensorDtype::Float32,
}];
const STEPMULTIPLIER_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "multiplier",
    shape: &[1, 1],
    dtype: TensorDtype::Float32,
}];

const WHRUNETENCODER_INPUTS: &[TensorSpec] = &[TensorSpec {
    name: "images",
    shape: &[1, 4, 128, 128],
    dtype: TensorDtype::Float32,
}];
const WHRUNETENCODER_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "features",
    shape: &[1, 2, 128, 128],
    dtype: TensorDtype::Float32,
}];

const WHRUNETHEAD_INPUTS: &[TensorSpec] = &[
    TensorSpec {
        name: "vectors",
        shape: &[1, 1, 128],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "scalars",
        shape: &[1, 7],
        dtype: TensorDtype::Float32,
    },
    TensorSpec {
        name: "features",
        shape: &[1, 2, 128, 128],
        dtype: TensorDtype::Float32,
    },
];
const WHRUNETHEAD_OUTPUTS: &[TensorSpec] = &[TensorSpec {
    name: "heart_rate",
    shape: &[1, 2, 128],
    dtype: TensorDtype::Float32,
}];

impl ModelId {
    /// The frozen contract for this model.
    pub const fn contract(self) -> ModelContract {
        match self {
            Self::ActivityContextEmbedding => ModelContract {
                id: Self::ActivityContextEmbedding,
                slug: "activity_context_embedding",
                algorithm_id: "activity_context_embedding",
                algorithm_version: Version::new(3, 1, 11),
                inputs: ACTIVITYCONTEXTEMBEDDING_INPUTS,
                outputs: ACTIVITYCONTEXTEMBEDDING_OUTPUTS,
                coreml_sha256: "619e26b88a6ec91e39df18fb4e426b6566c9c66c494731c961efc553e951fcff",
                tflite_sha256: "842ad2d5f75280f219eaac1a39205dc7ba63151e2fcbddf485ffa82de8fd9f69",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Embeds 85 context features per segment into a 312-d space",
            },
            Self::ActivityDetection => ModelContract {
                id: Self::ActivityDetection,
                slug: "activity_detection",
                algorithm_id: "automatic_activity_detection",
                algorithm_version: Version::new(3, 0, 8),
                inputs: ACTIVITYDETECTION_INPUTS,
                outputs: ACTIVITYDETECTION_OUTPUTS,
                coreml_sha256: "aad91b264a84e05e46e7c998da6be9eefaf8d7869959da8154b0a0449f7d99fd",
                tflite_sha256: "5bb6e57ca16bf5f328f0e1b5c5e74f6a03b2d0b5f7b653941f97a4b94d16a197",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Activity classification over 64 candidate segments of 77 features",
            },
            Self::ActivityEnsemble => ModelContract {
                id: Self::ActivityEnsemble,
                slug: "activity_ensemble",
                algorithm_id: "activity_ensemble",
                algorithm_version: Version::new(3, 1, 11),
                inputs: ACTIVITYENSEMBLE_INPUTS,
                outputs: ACTIVITYENSEMBLE_OUTPUTS,
                coreml_sha256: "d12cc6e51b32a2a17395f2edb049281f2ea0a1709f10e314bf881ddd9c7e08b7",
                tflite_sha256: "d3a0e319b063850f6cb06ce09de4a23bb988cc520e8f61376ec1000cb4ca5ba1",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Combines the primary and secondary segment heads into the final per-segment output",
            },
            Self::ActivityHistoryTransformer => ModelContract {
                id: Self::ActivityHistoryTransformer,
                slug: "activity_history_transformer",
                algorithm_id: "activity_history_transformer",
                algorithm_version: Version::new(3, 1, 11),
                inputs: ACTIVITYHISTORYTRANSFORMER_INPUTS,
                outputs: ACTIVITYHISTORYTRANSFORMER_OUTPUTS,
                coreml_sha256: "8a3f8e1aba3967b2bd0f28eee8b99d83a9cd45cae2eddcd9bbad634617b57081",
                tflite_sha256: "5ae0d644ed116890d069136bfff653feaf48522141c492aa43f886c0fab4ea63",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Self-attention over sixteen history segments; also returns its attention map",
            },
            Self::ActivityPrimarySegments => ModelContract {
                id: Self::ActivityPrimarySegments,
                slug: "activity_primary_segments",
                algorithm_id: "activity_primary_segments",
                algorithm_version: Version::new(3, 1, 11),
                inputs: ACTIVITYPRIMARYSEGMENTS_INPUTS,
                outputs: ACTIVITYPRIMARYSEGMENTS_OUTPUTS,
                coreml_sha256: "79109f2c130e970867dd4f1dad768ddaadfec7dc7d996137a15b289be447438c",
                tflite_sha256: "94267d6c57de8253298322b28548fe53a9c1d546a2d87b1d695c6482f27f8fc1",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Primary per-segment activity head",
            },
            Self::ActivitySecondarySegments => ModelContract {
                id: Self::ActivitySecondarySegments,
                slug: "activity_secondary_segments",
                algorithm_id: "activity_secondary_segments",
                algorithm_version: Version::new(3, 1, 11),
                inputs: ACTIVITYSECONDARYSEGMENTS_INPUTS,
                outputs: ACTIVITYSECONDARYSEGMENTS_OUTPUTS,
                coreml_sha256: "05e52d272bad4edd0a6d977fdee596078e3d8a7f4469d99597c23d2cbeb6cfc6",
                tflite_sha256: "32b2ed7dbd81a4433763be53bc627da9fa89d300a7fa7dd7f107f969176a75bb",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Secondary per-segment activity head, over the history encoder's output",
            },
            Self::ActivityTransition => ModelContract {
                id: Self::ActivityTransition,
                slug: "activity_transition",
                algorithm_id: "activity_transition_segmentation",
                algorithm_version: Version::new(3, 1, 11),
                inputs: ACTIVITYTRANSITION_INPUTS,
                outputs: ACTIVITYTRANSITION_OUTPUTS,
                coreml_sha256: "c00a67a9ee40a3dd4516a9291316b2eeb0b256527eb7fb48ea85b9d244457bdd",
                tflite_sha256: "4eb572738b956f0f79c28a59dbd1b7dd8b96c01767171c23856deca123ef9252",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Activity-transition segmentation over a 64-minute window",
            },
            Self::AwhrImputation => ModelContract {
                id: Self::AwhrImputation,
                slug: "awhr_imputation",
                algorithm_id: "awake_heart_rate_imputation",
                algorithm_version: Version::new(1, 2, 0),
                inputs: AWHRIMPUTATION_INPUTS,
                outputs: AWHRIMPUTATION_OUTPUTS,
                coreml_sha256: "240f31e5d2bc43118ee07485ca7956d75780f302b45649b9f7733204f15d3adc",
                tflite_sha256: "9a621a3f9741a06466943b1800e38a0319d85a765bfe12e04a7cfc967458ea32",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Bidirectional LSTM imputing awake heart rate over a 60-step context window",
            },
            Self::AwhrProfileCore => ModelContract {
                id: Self::AwhrProfileCore,
                slug: "awhr_profile_core",
                algorithm_id: "awake_heart_rate_profile",
                algorithm_version: Version::new(1, 0, 1),
                inputs: AWHRPROFILECORE_INPUTS,
                outputs: AWHRPROFILECORE_OUTPUTS,
                coreml_sha256: "4550a243ccad9f26eaba9544f6f1bc1bfeec22e46c10b8ec2926ad05fff7297a",
                tflite_sha256: "17efde1ac12f65c4b59033efd4714beb28b943d741dbe4ae95e46458a933483e",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Per-step activity features behind the awake-HR profile choice",
            },
            Self::AwhrProfileHead => ModelContract {
                id: Self::AwhrProfileHead,
                slug: "awhr_profile_head",
                algorithm_id: "awake_heart_rate_profile_head",
                algorithm_version: Version::new(1, 0, 1),
                inputs: AWHRPROFILEHEAD_INPUTS,
                outputs: AWHRPROFILEHEAD_OUTPUTS,
                coreml_sha256: "0ecc9552f92c45671f90d8ee1fd9920642bda57fb6af0ae1a0fe9b9ea4a85ca4",
                tflite_sha256: "f69957dd7f3b6c1d48c68d166c5b7ca04f0ee3437469b2880b0a876420a16fd3",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Three-way profile head over the recurrent layer's output",
            },
            Self::AwhrProfileRecurrent => ModelContract {
                id: Self::AwhrProfileRecurrent,
                slug: "awhr_profile_recurrent",
                algorithm_id: "awake_heart_rate_profile_recurrent",
                algorithm_version: Version::new(1, 0, 1),
                inputs: AWHRPROFILERECURRENT_INPUTS,
                outputs: AWHRPROFILERECURRENT_OUTPUTS,
                coreml_sha256: "64fbac5a09003c9ab4e1aa2f629beae1dc05486a8f104276574f27b2bda25469",
                tflite_sha256: "bdb3e5b14e4bcb89e9e07b854876d931b6a90114ca2cb2726d8fa1b7d8ab5dcb",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Bidirectional recurrent layer between the profile features and the profile head",
            },
            Self::BehaviorEmbedding => ModelContract {
                id: Self::BehaviorEmbedding,
                slug: "behavior_embedding",
                algorithm_id: "behavior_embedding",
                algorithm_version: Version::new(3, 1, 11),
                inputs: BEHAVIOREMBEDDING_INPUTS,
                outputs: BEHAVIOREMBEDDING_OUTPUTS,
                coreml_sha256: "9449b3d48267d8cfb35ebf71fac016d1f25e71e253ce3b2a46280c60b985255a",
                tflite_sha256: "c4071ac408da7dc1cdbd4b9fc6ca001c6be13e422d94114bb546020dbf3e0667",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Embeds sixteen behaviour ids into the activity model's 256-d space",
            },
            Self::CvaEncoder => ModelContract {
                id: Self::CvaEncoder,
                slug: "cva_encoder",
                algorithm_id: "cva_encoder",
                algorithm_version: Version::new(2, 1, 0),
                inputs: CVAENCODER_INPUTS,
                outputs: CVAENCODER_OUTPUTS,
                coreml_sha256: "b8003fad19a25db301b51a8c3083b8bf693d5740bd7dc610159ab501cca0874d",
                tflite_sha256: "4fbe89e6db08c5da8a0e98f3ff330cf81f9c4cab58c835d734f3e5559e462826",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "PPG transformer encoder: 1,024 normalised pulse samples to a 128-d embedding",
            },
            Self::CvaPredictorV1Base => ModelContract {
                id: Self::CvaPredictorV1Base,
                slug: "cva_predictor_v1_base",
                algorithm_id: "cva_predictor_v1_base",
                algorithm_version: Version::new(1, 3, 0),
                inputs: CVAPREDICTORV1BASE_INPUTS,
                outputs: CVAPREDICTORV1BASE_OUTPUTS,
                coreml_sha256: "2568173dc133f50b2b8ec3e28a3e64ddf51c580422a1fddeb78f1525c6cfeac9",
                tflite_sha256: "9bc367f802d4bb684fd08a882de8c9af12b234ff1ed85e9d779b7164c98a05f4",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Previous-generation CNN cardiovascular-age network over pulse, VPG and APG",
            },
            Self::CvaProbesFemale => ModelContract {
                id: Self::CvaProbesFemale,
                slug: "cva_probes_female",
                algorithm_id: "cva_probes",
                algorithm_version: Version::new(2, 1, 0),
                inputs: CVAPROBESFEMALE_INPUTS,
                outputs: CVAPROBESFEMALE_OUTPUTS,
                coreml_sha256: "7f2ed399a675c0febf287779419932f40b425f423d062a58c1a1fff1a8ad8df2",
                tflite_sha256: "b328ed6e5b8de4777448c1405ad6364f469c839a2c6497fed88670d78dc64f74",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "The female branch of the CVA probe head",
            },
            Self::CvaProbesMale => ModelContract {
                id: Self::CvaProbesMale,
                slug: "cva_probes_male",
                algorithm_id: "cva_probes",
                algorithm_version: Version::new(2, 1, 0),
                inputs: CVAPROBESMALE_INPUTS,
                outputs: CVAPROBESMALE_OUTPUTS,
                coreml_sha256: "b7cca22b76e02ea1cd24787caa584ecee8d48b5d7a14d02d55b332c61a5ed669",
                tflite_sha256: "fd4b9a282f00d8457aa981a6d0ae5e7cb3c806a859bf325cbb6c473c93f5503c",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Cardiovascular age, pulse-wave velocity and blood pressure from a CVA embedding",
            },
            Self::DhrvImputation => ModelContract {
                id: Self::DhrvImputation,
                slug: "dhrv_imputation",
                algorithm_id: "daytime_hrv_imputation",
                algorithm_version: Version::new(1, 1, 0),
                inputs: DHRVIMPUTATION_INPUTS,
                outputs: DHRVIMPUTATION_OUTPUTS,
                coreml_sha256: "5dfadac3b7aa3a24d0aa1575d9c3924b8b9a0cdffc7b570169e3462f42fb6132",
                tflite_sha256: "acb2e38d48aa8789f39692b933d08f668f2402545d92a97cecb8c7b8b2127f45",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Daytime HRV imputation from temperature, MET, HR and their baselines",
            },
            Self::EnergyExpenditureHr => ModelContract {
                id: Self::EnergyExpenditureHr,
                slug: "energy_expenditure_hr",
                algorithm_id: "energy_expenditure_hr",
                algorithm_version: Version::new(1, 0, 0),
                inputs: ENERGYEXPENDITUREHR_INPUTS,
                outputs: ENERGYEXPENDITUREHR_OUTPUTS,
                coreml_sha256: "82c4e4991c29d3c4603ecfd515e11d7a8a98af5b2361a7c30b64733645c1a5c8",
                tflite_sha256: "55874df93c68b2c393262d13d5da3bb2bc13ee3a074ae9629188ab39b813cf01",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Active energy expenditure for a window where heart rate is available",
            },
            Self::EnergyExpenditureNoHr => ModelContract {
                id: Self::EnergyExpenditureNoHr,
                slug: "energy_expenditure_no_hr",
                algorithm_id: "energy_expenditure_no_hr",
                algorithm_version: Version::new(1, 0, 0),
                inputs: ENERGYEXPENDITURENOHR_INPUTS,
                outputs: ENERGYEXPENDITURENOHR_OUTPUTS,
                coreml_sha256: "22a8747d23e31d32a3c64ba6e69c12aa5dfe876fa0be8f16e3377d86c1dabc42",
                tflite_sha256: "6bf1ae7f18ca18ec7c3ae216f754beff38374cfa4ff7f4ab9ebe5af1d9fc9003",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Active energy expenditure for a window with no usable heart rate",
            },
            Self::HalitePpgScore => ModelContract {
                id: Self::HalitePpgScore,
                slug: "halite_ppg_score",
                algorithm_id: "halite_ppg_score",
                algorithm_version: Version::new(1, 2, 0),
                inputs: HALITEPPGSCORE_INPUTS,
                outputs: HALITEPPGSCORE_OUTPUTS,
                coreml_sha256: "f2e8992d404f89c368a48484fa46678b80749ad74b24c8d21728ab92a8e70eff",
                tflite_sha256: "59fa620a549d1cce51d23876c7b7f990a51bae17411d7b22cd13a728a16688bc",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Scores one PulseNet embedding into the hypertension-risk PPG score",
            },
            Self::HaliteRiskTree => ModelContract {
                id: Self::HaliteRiskTree,
                slug: "halite_risk_tree",
                algorithm_id: "halite_hypertension_risk",
                algorithm_version: Version::new(1, 2, 0),
                inputs: HALITERISKTREE_INPUTS,
                outputs: HALITERISKTREE_OUTPUTS,
                coreml_sha256: "d31b0f24d2778cb7a4ac68dd3fc70c94f93222df788689d537f124d0a9c1790d",
                tflite_sha256: "b7d4e75090e2dd98067277a2ad7572bd6f0ede686addc80416461f002d08d4a5",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Gradient-boosted head over user info, baselines and the aggregated PPG score",
            },
            Self::IllnessDetection => ModelContract {
                id: Self::IllnessDetection,
                slug: "illness_detection",
                algorithm_id: "illness_detection",
                algorithm_version: Version::new(0, 5, 1),
                inputs: ILLNESSDETECTION_INPUTS,
                outputs: ILLNESSDETECTION_OUTPUTS,
                coreml_sha256: "ddb8019a41dff458cbb59be1c05a40918d31708f205f2eb4e302addf6cb18ba5",
                tflite_sha256: "6f8e91b7bd653c1fc6a1b210e46819eb62dc5f55ed973ff8a3c3cad96d5246d0",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Illness likelihood from thirty days of eight daily biometric deviations",
            },
            Self::PopsicleMinFollicular => ModelContract {
                id: Self::PopsicleMinFollicular,
                slug: "popsicle_min_follicular",
                algorithm_id: "popsicle_min_follicular",
                algorithm_version: Version::new(1, 8, 1),
                inputs: POPSICLEMINFOLLICULAR_INPUTS,
                outputs: POPSICLEMINFOLLICULAR_OUTPUTS,
                coreml_sha256: "c4a4b3560d19f71618a1f54b2276c7f6b7e3ab0d6e4b877f07ed383ef208655b",
                tflite_sha256: "54c55f54ab37cfb603a38da64528f817e227122e55fbadfe35cf9b2a168bb69f",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Predicts the shortest plausible follicular phase for this wearer",
            },
            Self::PopsicleMinFollicularV16 => ModelContract {
                id: Self::PopsicleMinFollicularV16,
                slug: "popsicle_min_follicular_v16",
                algorithm_id: "popsicle_min_follicular",
                algorithm_version: Version::new(1, 6, 0),
                inputs: POPSICLEMINFOLLICULARV16_INPUTS,
                outputs: POPSICLEMINFOLLICULARV16_OUTPUTS,
                coreml_sha256: "6b50ae16ea245a418e021f4b7bc3680fb6776e882993925cf351972bd9442e95",
                tflite_sha256: "54c55f54ab37cfb603a38da64528f817e227122e55fbadfe35cf9b2a168bb69f",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "The previous generation of the follicular-length head",
            },
            Self::PopsicleOvulationDetection => ModelContract {
                id: Self::PopsicleOvulationDetection,
                slug: "popsicle_ovulation_detection",
                algorithm_id: "popsicle_ovulation_detection",
                algorithm_version: Version::new(1, 8, 1),
                inputs: POPSICLEOVULATIONDETECTION_INPUTS,
                outputs: POPSICLEOVULATIONDETECTION_OUTPUTS,
                coreml_sha256: "babc1c20c80f04c6cb149f84946b0c5bcc14df5c91c3c2559c564829197d3215",
                tflite_sha256: "7ff9f985b7542f0865d1ae32cc8a0ff4bb17bd82441471dd13efa380c50a35a0",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Ovulation detection over up to forty cycle days of temperature, heart rate and breath rate",
            },
            Self::PopsicleOvulationDetectionV16 => ModelContract {
                id: Self::PopsicleOvulationDetectionV16,
                slug: "popsicle_ovulation_detection_v16",
                algorithm_id: "popsicle_ovulation_detection",
                algorithm_version: Version::new(1, 6, 0),
                inputs: POPSICLEOVULATIONDETECTIONV16_INPUTS,
                outputs: POPSICLEOVULATIONDETECTIONV16_OUTPUTS,
                coreml_sha256: "e0ea4e355db7910a0b26835b5790920e6d715e7fa666c5e84fc2c74c3be5a8c2",
                tflite_sha256: "2e244193a3069b632c00934a15f506f6e8de7efd7adae9b50dd1ea1e04077054",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "The previous generation of the ovulation detector",
            },
            Self::PopsicleOvulationPrediction => ModelContract {
                id: Self::PopsicleOvulationPrediction,
                slug: "popsicle_ovulation_prediction",
                algorithm_id: "popsicle_ovulation_prediction",
                algorithm_version: Version::new(1, 8, 1),
                inputs: POPSICLEOVULATIONPREDICTION_INPUTS,
                outputs: POPSICLEOVULATIONPREDICTION_OUTPUTS,
                coreml_sha256: "e16b16ab850c8121e0d2e93140f6a8e3e7dfeaa40f0123b069366ef3d7c87949",
                tflite_sha256: "3ff28f25ad2559d068126d41a469f22a0d18be735f32a86437e9aee96cbbaf3f",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Days until the next ovulation, per cycle day",
            },
            Self::PopsicleOvulationPredictionV16 => ModelContract {
                id: Self::PopsicleOvulationPredictionV16,
                slug: "popsicle_ovulation_prediction_v16",
                algorithm_id: "popsicle_ovulation_prediction",
                algorithm_version: Version::new(1, 6, 0),
                inputs: POPSICLEOVULATIONPREDICTIONV16_INPUTS,
                outputs: POPSICLEOVULATIONPREDICTIONV16_OUTPUTS,
                coreml_sha256: "a64e1c8565ef2f9fe5662b5211393bc1a528c715bf50019951c67a074dd0610a",
                tflite_sha256: "d8139c89cf715f16b6a9c41e54b3e5f849c75f908bc8462ff7a019cf670cc9bc",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "The previous generation of the ovulation predictor",
            },
            Self::PopsiclePeriodPrediction => ModelContract {
                id: Self::PopsiclePeriodPrediction,
                slug: "popsicle_period_prediction",
                algorithm_id: "popsicle_period_prediction",
                algorithm_version: Version::new(1, 8, 1),
                inputs: POPSICLEPERIODPREDICTION_INPUTS,
                outputs: POPSICLEPERIODPREDICTION_OUTPUTS,
                coreml_sha256: "a57c8ef558767ad1c45bada412b6a7eecc0e692a8d39ceca4130bac87c758811",
                tflite_sha256: "aa3265e7c82faa1a19f46fc1594ae49cd6a5faad439b992150d31ca9e1e2c1e5",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Days until the next period, per cycle day",
            },
            Self::PopsiclePeriodPredictionV16 => ModelContract {
                id: Self::PopsiclePeriodPredictionV16,
                slug: "popsicle_period_prediction_v16",
                algorithm_id: "popsicle_period_prediction",
                algorithm_version: Version::new(1, 6, 0),
                inputs: POPSICLEPERIODPREDICTIONV16_INPUTS,
                outputs: POPSICLEPERIODPREDICTIONV16_OUTPUTS,
                coreml_sha256: "2814ec41deb31e7e5ed5e16d8b15156e840dff8a94192f8ea12466a2a59d4834",
                tflite_sha256: "f6853eadbab0f79d77d65f5bdf3928ddbacf42f89b021217a481bf1e746ebc00",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "The previous generation of the period predictor",
            },
            Self::PulsePpg => ModelContract {
                id: Self::PulsePpg,
                slug: "pulse_ppg",
                algorithm_id: "pulse_ppg_embeddings",
                algorithm_version: Version::new(1, 0, 0),
                inputs: PULSEPPG_INPUTS,
                outputs: PULSEPPG_OUTPUTS,
                coreml_sha256: "568ac0eeb548663db4a0f25375d45aefb4a4289fa3e8c607713bd10e30c1a354",
                tflite_sha256: "4d6359ab1e37d7a47bb4ff94ca74fe2b19604283dcdece0a256a48ea440c78fb",
                standing: ModelStanding::OpenLicensed,
                licence: "MIT (Pulse-PPG, Xu et al., UbiComp 2025)",
                role: "Open-weight PPG foundation encoder: 240 s at 50 Hz to a 512-d embedding, pre-trained on uncurated field PPG",
            },
            Self::PulsenetFoundation => ModelContract {
                id: Self::PulsenetFoundation,
                slug: "pulsenet_foundation",
                algorithm_id: "pulsenet_foundation_embeddings",
                algorithm_version: Version::new(0, 4, 0),
                inputs: PULSENETFOUNDATION_INPUTS,
                outputs: PULSENETFOUNDATION_OUTPUTS,
                coreml_sha256: "92e7093ff85882a7d9d5621eef9e3121b42dd1d11ee9e15319ca3623dd0454ff",
                tflite_sha256: "7f7860c0ad92c14772af463a678a9df35f0034bff566e792e8cc491c9d1f6ad8",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "PPG foundation encoder: 30 s of detrended PPG at 50 Hz to a 256-d embedding",
            },
            Self::SleepnetBdi => ModelContract {
                id: Self::SleepnetBdi,
                slug: "sleepnet_bdi",
                algorithm_id: "sleepnet_bdi",
                algorithm_version: Version::new(0, 4, 0),
                inputs: SLEEPNETBDI_INPUTS,
                outputs: SLEEPNETBDI_OUTPUTS,
                coreml_sha256: "46480a9b1907c7193e5c7bc1258e6098ef4cb9994580600acecf397c1ae7d7a2",
                tflite_sha256: "590469f28981207650001b833089219386284383ede29fda9d64f56465659769",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Sleep stages and apnea events from interbeat intervals alone",
            },
            Self::SleepnetBdiV3 => ModelContract {
                id: Self::SleepnetBdiV3,
                slug: "sleepnet_bdi_v3",
                algorithm_id: "sleepnet_bdi",
                algorithm_version: Version::new(0, 3, 0),
                inputs: SLEEPNETBDIV3_INPUTS,
                outputs: SLEEPNETBDIV3_OUTPUTS,
                coreml_sha256: "911c44310cd6a04deba5d9eb716bc92b387cc539b81211ff7dde690b9747d0c4",
                tflite_sha256: "dd144e71757fe443b587f95b947a89c54790654d8c5eef9392adae97f5e7b4a4",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Previous-generation interbeat-interval sleep-staging network",
            },
            Self::SleepnetMoonstone => ModelContract {
                id: Self::SleepnetMoonstone,
                slug: "sleepnet_moonstone",
                algorithm_id: "sleepnet_moonstone",
                algorithm_version: Version::new(1, 2, 0),
                inputs: SLEEPNETMOONSTONE_INPUTS,
                outputs: SLEEPNETMOONSTONE_OUTPUTS,
                coreml_sha256: "74450f57791b41af9b30ab97f883af11996ab0b3a95501630ed93f51dee146ca",
                tflite_sha256: "ae635931514d09f53607b80acc72acae36038b3f16c12e7d0ad2abac8b277d2d",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Sleep stages, apnea and SpO2 events over a 15-hour night",
            },
            Self::SourceEmbedding => ModelContract {
                id: Self::SourceEmbedding,
                slug: "source_embedding",
                algorithm_id: "activity_source_embedding",
                algorithm_version: Version::new(3, 1, 11),
                inputs: SOURCEEMBEDDING_INPUTS,
                outputs: SOURCEEMBEDDING_OUTPUTS,
                coreml_sha256: "0c63d3c6e643cdae7b004a4dd171705e096b737bd916bd7b1f7c657cda55e478",
                tflite_sha256: "84a1d9a9b6fa7c6523912801190faece00c579afa6c59e66fb145de4c35d14b8",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Embeds each segment's provenance — how the activity was recorded — into eight values",
            },
            Self::StepEligibility => ModelContract {
                id: Self::StepEligibility,
                slug: "step_eligibility",
                algorithm_id: "step_eligibility",
                algorithm_version: Version::new(1, 3, 0),
                inputs: STEPELIGIBILITY_INPUTS,
                outputs: STEPELIGIBILITY_OUTPUTS,
                coreml_sha256: "7a687c7e85736fa3e8668f90f13650e6248f649f1691c79f9c9690e5f77b6095",
                tflite_sha256: "b33af52edeaa6671af7cd9075308c8d986e3ea5b4cf964244b4f8a562eefff68",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Step-eligibility features from one step-motion vector",
            },
            Self::StepHead => ModelContract {
                id: Self::StepHead,
                slug: "step_head",
                algorithm_id: "step_eligibility_head",
                algorithm_version: Version::new(1, 3, 0),
                inputs: STEPHEAD_INPUTS,
                outputs: STEPHEAD_OUTPUTS,
                coreml_sha256: "e84b32bb41998dbe48102063e3acd660a4ba394b6d037b86e7c25bd503b806c9",
                tflite_sha256: "09f1045c6644d8b6296b5a80132f9be20267ffda0187791bf824ad92a7d75008",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Turns the eligibility features into one eligibility score",
            },
            Self::StepMultiplier => ModelContract {
                id: Self::StepMultiplier,
                slug: "step_multiplier",
                algorithm_id: "step_count_multiplier",
                algorithm_version: Version::new(1, 3, 0),
                inputs: STEPMULTIPLIER_INPUTS,
                outputs: STEPMULTIPLIER_OUTPUTS,
                coreml_sha256: "7861cf28e0c8d045319a58a4f4055e3ee70cbe92d763e62b4f23f834cd8bda89",
                tflite_sha256: "fb966f78975654198304b8391c1827b423427962acf262f08ed6748c5b37abbb",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Parameterised sigmoid scaling the raw step count by eligibility",
            },
            Self::WhrUnetEncoder => ModelContract {
                id: Self::WhrUnetEncoder,
                slug: "whr_unet_encoder",
                algorithm_id: "workout_heart_rate_unet",
                algorithm_version: Version::new(2, 7, 1),
                inputs: WHRUNETENCODER_INPUTS,
                outputs: WHRUNETENCODER_OUTPUTS,
                coreml_sha256: "fb6779598f631eeca2ceaa1e4909d05508911532f317304c580634cbdee04172",
                tflite_sha256: "77d297aa6b3eb1e012c3a6d36ac73004788b367e689b9bc7282326f1f506805f",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "U-Net over the workout PPG spectrogram window",
            },
            Self::WhrUnetHead => ModelContract {
                id: Self::WhrUnetHead,
                slug: "whr_unet_head",
                algorithm_id: "workout_heart_rate_head",
                algorithm_version: Version::new(2, 7, 1),
                inputs: WHRUNETHEAD_INPUTS,
                outputs: WHRUNETHEAD_OUTPUTS,
                coreml_sha256: "90a6898d07507935ee69b6bfb3e85280190303db830ebea99fe3123c245ae5d7",
                tflite_sha256: "e9285794934e2b53f5d6b2c2301e4e88cbc718f1ce34fbfce19b8155dc0942d7",
                standing: ModelStanding::FirstParty,
                licence: "Maverick first-party weights",
                role: "Recurrent head turning U-Net features into a per-column heart rate",
            },
        }
    }

    /// Resolve a model from the slug the platform layer uses as its artefact name.
    pub fn from_slug(slug: &str) -> Option<Self> {
        match slug {
            "activity_context_embedding" => Some(Self::ActivityContextEmbedding),
            "activity_detection" => Some(Self::ActivityDetection),
            "activity_ensemble" => Some(Self::ActivityEnsemble),
            "activity_history_transformer" => Some(Self::ActivityHistoryTransformer),
            "activity_primary_segments" => Some(Self::ActivityPrimarySegments),
            "activity_secondary_segments" => Some(Self::ActivitySecondarySegments),
            "activity_transition" => Some(Self::ActivityTransition),
            "awhr_imputation" => Some(Self::AwhrImputation),
            "awhr_profile_core" => Some(Self::AwhrProfileCore),
            "awhr_profile_head" => Some(Self::AwhrProfileHead),
            "awhr_profile_recurrent" => Some(Self::AwhrProfileRecurrent),
            "behavior_embedding" => Some(Self::BehaviorEmbedding),
            "cva_encoder" => Some(Self::CvaEncoder),
            "cva_predictor_v1_base" => Some(Self::CvaPredictorV1Base),
            "cva_probes_female" => Some(Self::CvaProbesFemale),
            "cva_probes_male" => Some(Self::CvaProbesMale),
            "dhrv_imputation" => Some(Self::DhrvImputation),
            "energy_expenditure_hr" => Some(Self::EnergyExpenditureHr),
            "energy_expenditure_no_hr" => Some(Self::EnergyExpenditureNoHr),
            "halite_ppg_score" => Some(Self::HalitePpgScore),
            "halite_risk_tree" => Some(Self::HaliteRiskTree),
            "illness_detection" => Some(Self::IllnessDetection),
            "popsicle_min_follicular" => Some(Self::PopsicleMinFollicular),
            "popsicle_min_follicular_v16" => Some(Self::PopsicleMinFollicularV16),
            "popsicle_ovulation_detection" => Some(Self::PopsicleOvulationDetection),
            "popsicle_ovulation_detection_v16" => Some(Self::PopsicleOvulationDetectionV16),
            "popsicle_ovulation_prediction" => Some(Self::PopsicleOvulationPrediction),
            "popsicle_ovulation_prediction_v16" => Some(Self::PopsicleOvulationPredictionV16),
            "popsicle_period_prediction" => Some(Self::PopsiclePeriodPrediction),
            "popsicle_period_prediction_v16" => Some(Self::PopsiclePeriodPredictionV16),
            "pulse_ppg" => Some(Self::PulsePpg),
            "pulsenet_foundation" => Some(Self::PulsenetFoundation),
            "sleepnet_bdi" => Some(Self::SleepnetBdi),
            "sleepnet_bdi_v3" => Some(Self::SleepnetBdiV3),
            "sleepnet_moonstone" => Some(Self::SleepnetMoonstone),
            "source_embedding" => Some(Self::SourceEmbedding),
            "step_eligibility" => Some(Self::StepEligibility),
            "step_head" => Some(Self::StepHead),
            "step_multiplier" => Some(Self::StepMultiplier),
            "whr_unet_encoder" => Some(Self::WhrUnetEncoder),
            "whr_unet_head" => Some(Self::WhrUnetHead),
            _ => None,
        }
    }
}
