// Generated by tools/ml/generate_bindings.py from artifacts/models/manifest.json. Do not edit.

import CoreML
import Foundation

/// The Core ML artefacts this build ships, and the tensor contract each one binds to.
///
/// `admittedSHA256` is the hash of the `model.mlmodel` inside the source `.mlpackage`.
/// Xcode compiles that package to an `.mlmodelc`, so the running app cannot re-derive
/// the hash; `tools/check_model_assets.py` proves the shipped package matches this
/// value, and the runner reports it to core so an unadmitted build fails closed.
enum MavModelCatalog {
  struct TensorSpec {
    let name: String
    let shape: [Int]
    var elementCount: Int { shape.reduce(1, *) }
  }

  /// Which compute units this model was admitted under.
  ///
  /// Not a performance hint. Core ML's backends do not agree with each other on
  /// every graph: the sleep models are exact on the CPU and on the Neural Engine
  /// and wrong by more than one whole relative unit on the GPU, at every
  /// precision. Each model records the configuration its parity was measured
  /// under, and the runner uses that one.
  enum ComputeUnits: String {
    case all
    case cpuAndNeuralEngine
    case cpuAndGPU
    case cpuOnly

    var mlComputeUnits: MLComputeUnits {
      switch self {
      case .all: .all
      case .cpuAndNeuralEngine: .cpuAndNeuralEngine
      case .cpuAndGPU: .cpuAndGPU
      case .cpuOnly: .cpuOnly
      }
    }
  }

  struct Entry {
    let slug: String
    let admittedSHA256: String
    let computeUnits: ComputeUnits
    let inputs: [TensorSpec]
    let outputs: [TensorSpec]
  }

  static let entries: [String: Entry] = [
    "activity_context_embedding": Entry(
      slug: "activity_context_embedding",
      admittedSHA256: "619e26b88a6ec91e39df18fb4e426b6566c9c66c494731c961efc553e951fcff",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "context", shape: [1, 16, 85]),
      ],
      outputs: [
        TensorSpec(name: "embeddings", shape: [1, 16, 312]),
      ]
    ),
    "activity_detection": Entry(
      slug: "activity_detection",
      admittedSHA256: "aad91b264a84e05e46e7c998da6be9eefaf8d7869959da8154b0a0449f7d99fd",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "features", shape: [1, 64, 77]),
      ],
      outputs: [
        TensorSpec(name: "activity_output", shape: [1, 64, 262]),
      ]
    ),
    "activity_ensemble": Entry(
      slug: "activity_ensemble",
      admittedSHA256: "d12cc6e51b32a2a17395f2edb049281f2ea0a1709f10e314bf881ddd9c7e08b7",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "primary", shape: [1, 16, 260]),
        TensorSpec(name: "secondary", shape: [1, 16, 260]),
      ],
      outputs: [
        TensorSpec(name: "segment_output", shape: [1, 16, 260]),
      ]
    ),
    "activity_history_transformer": Entry(
      slug: "activity_history_transformer",
      admittedSHA256: "8a3f8e1aba3967b2bd0f28eee8b99d83a9cd45cae2eddcd9bbad634617b57081",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "segments", shape: [1, 16, 573]),
      ],
      outputs: [
        TensorSpec(name: "encoded", shape: [1, 16, 336]),
        TensorSpec(name: "attention", shape: [1, 1, 6, 16, 18]),
      ]
    ),
    "activity_primary_segments": Entry(
      slug: "activity_primary_segments",
      admittedSHA256: "79109f2c130e970867dd4f1dad768ddaadfec7dc7d996137a15b289be447438c",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "features", shape: [1, 16, 110]),
      ],
      outputs: [
        TensorSpec(name: "segment_output", shape: [1, 16, 260]),
      ]
    ),
    "activity_secondary_segments": Entry(
      slug: "activity_secondary_segments",
      admittedSHA256: "05e52d272bad4edd0a6d977fdee596078e3d8a7f4469d99597c23d2cbeb6cfc6",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "features", shape: [1, 16, 336]),
      ],
      outputs: [
        TensorSpec(name: "segment_output", shape: [1, 16, 260]),
      ]
    ),
    "activity_transition": Entry(
      slug: "activity_transition",
      admittedSHA256: "c00a67a9ee40a3dd4516a9291316b2eeb0b256527eb7fb48ea85b9d244457bdd",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "features", shape: [1, 64, 29]),
      ],
      outputs: [
        TensorSpec(name: "transition_logits", shape: [1, 64]),
      ]
    ),
    "awhr_imputation": Entry(
      slug: "awhr_imputation",
      admittedSHA256: "240f31e5d2bc43118ee07485ca7956d75780f302b45649b9f7733204f15d3adc",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "window", shape: [1, 60, 13]),
      ],
      outputs: [
        TensorSpec(name: "imputed_hr", shape: [1, 60, 1]),
      ]
    ),
    "awhr_profile_core": Entry(
      slug: "awhr_profile_core",
      admittedSHA256: "4550a243ccad9f26eaba9544f6f1bc1bfeec22e46c10b8ec2926ad05fff7297a",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "features", shape: [60, 19]),
      ],
      outputs: [
        TensorSpec(name: "profile_features", shape: [60, 6]),
      ]
    ),
    "awhr_profile_head": Entry(
      slug: "awhr_profile_head",
      admittedSHA256: "0ecc9552f92c45671f90d8ee1fd9920642bda57fb6af0ae1a0fe9b9ea4a85ca4",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "features", shape: [60, 32]),
      ],
      outputs: [
        TensorSpec(name: "profile_logits", shape: [60, 3]),
      ]
    ),
    "awhr_profile_recurrent": Entry(
      slug: "awhr_profile_recurrent",
      admittedSHA256: "64fbac5a09003c9ab4e1aa2f629beae1dc05486a8f104276574f27b2bda25469",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "features", shape: [1, 60, 6]),
      ],
      outputs: [
        TensorSpec(name: "encoded", shape: [1, 60, 32]),
      ]
    ),
    "behavior_embedding": Entry(
      slug: "behavior_embedding",
      admittedSHA256: "9449b3d48267d8cfb35ebf71fac016d1f25e71e253ce3b2a46280c60b985255a",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "behavior_ids", shape: [1, 16]),
      ],
      outputs: [
        TensorSpec(name: "embeddings", shape: [1, 16, 256]),
      ]
    ),
    "cva_encoder": Entry(
      slug: "cva_encoder",
      admittedSHA256: "b8003fad19a25db301b51a8c3083b8bf693d5740bd7dc610159ab501cca0874d",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "pulses", shape: [1, 1024]),
      ],
      outputs: [
        TensorSpec(name: "embeddings", shape: [1, 128]),
      ]
    ),
    "cva_predictor_v1_base": Entry(
      slug: "cva_predictor_v1_base",
      admittedSHA256: "2568173dc133f50b2b8ec3e28a3e64ddf51c580422a1fddeb78f1525c6cfeac9",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "pulse_triple", shape: [1, 3, 256]),
        TensorSpec(name: "exogenous", shape: [1, 8]),
      ],
      outputs: [
        TensorSpec(name: "cva", shape: [1, 1]),
        TensorSpec(name: "pwv", shape: [1, 1]),
        TensorSpec(name: "features", shape: [1, 272]),
      ]
    ),
    "cva_probes_female": Entry(
      slug: "cva_probes_female",
      admittedSHA256: "7f2ed399a675c0febf287779419932f40b425f423d062a58c1a1fff1a8ad8df2",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "embeddings", shape: [1, 128]),
        TensorSpec(name: "age", shape: [1]),
        TensorSpec(name: "weight", shape: [1]),
        TensorSpec(name: "bmi", shape: [1]),
      ],
      outputs: [
        TensorSpec(name: "cva", shape: [1]),
        TensorSpec(name: "pwv", shape: [1]),
        TensorSpec(name: "systolic", shape: [1]),
        TensorSpec(name: "diastolic", shape: [1]),
      ]
    ),
    "cva_probes_male": Entry(
      slug: "cva_probes_male",
      admittedSHA256: "b7cca22b76e02ea1cd24787caa584ecee8d48b5d7a14d02d55b332c61a5ed669",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "embeddings", shape: [1, 128]),
        TensorSpec(name: "age", shape: [1]),
        TensorSpec(name: "weight", shape: [1]),
        TensorSpec(name: "bmi", shape: [1]),
      ],
      outputs: [
        TensorSpec(name: "cva", shape: [1]),
        TensorSpec(name: "pwv", shape: [1]),
        TensorSpec(name: "systolic", shape: [1]),
        TensorSpec(name: "diastolic", shape: [1]),
      ]
    ),
    "dhrv_imputation": Entry(
      slug: "dhrv_imputation",
      admittedSHA256: "5dfadac3b7aa3a24d0aa1575d9c3924b8b9a0cdffc7b570169e3462f42fb6132",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "features", shape: [1, 10]),
      ],
      outputs: [
        TensorSpec(name: "imputed_dhrv", shape: [1, 1]),
      ]
    ),
    "energy_expenditure_hr": Entry(
      slug: "energy_expenditure_hr",
      admittedSHA256: "82c4e4991c29d3c4603ecfd515e11d7a8a98af5b2361a7c30b64733645c1a5c8",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "features", shape: [1, 50]),
      ],
      outputs: [
        TensorSpec(name: "energy", shape: [1, 1]),
      ]
    ),
    "energy_expenditure_no_hr": Entry(
      slug: "energy_expenditure_no_hr",
      admittedSHA256: "22a8747d23e31d32a3c64ba6e69c12aa5dfe876fa0be8f16e3377d86c1dabc42",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "features", shape: [1, 42]),
      ],
      outputs: [
        TensorSpec(name: "energy", shape: [1, 1]),
      ]
    ),
    "halite_ppg_score": Entry(
      slug: "halite_ppg_score",
      admittedSHA256: "f2e8992d404f89c368a48484fa46678b80749ad74b24c8d21728ab92a8e70eff",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "embeddings", shape: [1, 256]),
      ],
      outputs: [
        TensorSpec(name: "ppg_score", shape: [1, 1]),
      ]
    ),
    "halite_risk_tree": Entry(
      slug: "halite_risk_tree",
      admittedSHA256: "d31b0f24d2778cb7a4ac68dd3fc70c94f93222df788689d537f124d0a9c1790d",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "features", shape: [1, 13]),
      ],
      outputs: [
        TensorSpec(name: "label", shape: [1]),
        TensorSpec(name: "probabilities", shape: [1, 2]),
      ]
    ),
    "illness_detection": Entry(
      slug: "illness_detection",
      admittedSHA256: "ddb8019a41dff458cbb59be1c05a40918d31708f205f2eb4e302addf6cb18ba5",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "scalars", shape: [1, 4]),
        TensorSpec(name: "time_series", shape: [1, 8, 30]),
      ],
      outputs: [
        TensorSpec(name: "illness_probability", shape: [1, 1]),
      ]
    ),
    "popsicle_min_follicular": Entry(
      slug: "popsicle_min_follicular",
      admittedSHA256: "c4a4b3560d19f71618a1f54b2276c7f6b7e3ab0d6e4b877f07ed383ef208655b",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "features", shape: [1, 9]),
      ],
      outputs: [
        TensorSpec(name: "min_follicular_days", shape: [1, 1]),
      ]
    ),
    "popsicle_min_follicular_v16": Entry(
      slug: "popsicle_min_follicular_v16",
      admittedSHA256: "6b50ae16ea245a418e021f4b7bc3680fb6776e882993925cf351972bd9442e95",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "features", shape: [1, 9]),
      ],
      outputs: [
        TensorSpec(name: "min_follicular_days", shape: [1, 1]),
      ]
    ),
    "popsicle_ovulation_detection": Entry(
      slug: "popsicle_ovulation_detection",
      admittedSHA256: "babc1c20c80f04c6cb149f84946b0c5bcc14df5c91c3c2559c564829197d3215",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "time_series", shape: [1, 40, 3]),
        TensorSpec(name: "scalars", shape: [1, 40, 4]),
      ],
      outputs: [
        TensorSpec(name: "ovulation_probability", shape: [1, 40, 1]),
      ]
    ),
    "popsicle_ovulation_detection_v16": Entry(
      slug: "popsicle_ovulation_detection_v16",
      admittedSHA256: "e0ea4e355db7910a0b26835b5790920e6d715e7fa666c5e84fc2c74c3be5a8c2",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "time_series", shape: [1, 40, 3]),
        TensorSpec(name: "scalars", shape: [1, 40, 4]),
      ],
      outputs: [
        TensorSpec(name: "ovulation_probability", shape: [1, 40, 1]),
      ]
    ),
    "popsicle_ovulation_prediction": Entry(
      slug: "popsicle_ovulation_prediction",
      admittedSHA256: "e16b16ab850c8121e0d2e93140f6a8e3e7dfeaa40f0123b069366ef3d7c87949",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "time_series", shape: [1, 40, 3]),
        TensorSpec(name: "scalars", shape: [1, 40, 4]),
      ],
      outputs: [
        TensorSpec(name: "days", shape: [1, 40, 1]),
      ]
    ),
    "popsicle_ovulation_prediction_v16": Entry(
      slug: "popsicle_ovulation_prediction_v16",
      admittedSHA256: "a64e1c8565ef2f9fe5662b5211393bc1a528c715bf50019951c67a074dd0610a",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "time_series", shape: [1, 40, 3]),
        TensorSpec(name: "scalars", shape: [1, 40, 4]),
      ],
      outputs: [
        TensorSpec(name: "days", shape: [1, 40, 1]),
      ]
    ),
    "popsicle_period_prediction": Entry(
      slug: "popsicle_period_prediction",
      admittedSHA256: "a57c8ef558767ad1c45bada412b6a7eecc0e692a8d39ceca4130bac87c758811",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "time_series", shape: [1, 40, 3]),
        TensorSpec(name: "scalars", shape: [1, 40, 4]),
      ],
      outputs: [
        TensorSpec(name: "days", shape: [1, 40, 1]),
      ]
    ),
    "popsicle_period_prediction_v16": Entry(
      slug: "popsicle_period_prediction_v16",
      admittedSHA256: "2814ec41deb31e7e5ed5e16d8b15156e840dff8a94192f8ea12466a2a59d4834",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "time_series", shape: [1, 40, 3]),
        TensorSpec(name: "scalars", shape: [1, 40, 4]),
      ],
      outputs: [
        TensorSpec(name: "days", shape: [1, 40, 1]),
      ]
    ),
    "pulse_ppg": Entry(
      slug: "pulse_ppg",
      admittedSHA256: "568ac0eeb548663db4a0f25375d45aefb4a4289fa3e8c607713bd10e30c1a354",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "ppg", shape: [1, 1, 12000]),
      ],
      outputs: [
        TensorSpec(name: "embeddings", shape: [1, 512]),
      ]
    ),
    "pulsenet_foundation": Entry(
      slug: "pulsenet_foundation",
      admittedSHA256: "92e7093ff85882a7d9d5621eef9e3121b42dd1d11ee9e15319ca3623dd0454ff",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "ppg", shape: [1, 1, 1500]),
      ],
      outputs: [
        TensorSpec(name: "embeddings", shape: [1, 256]),
      ]
    ),
    "sleepnet_bdi": Entry(
      slug: "sleepnet_bdi",
      admittedSHA256: "46480a9b1907c7193e5c7bc1258e6098ef4cb9994580600acecf397c1ae7d7a2",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "high_res", shape: [1, 115200, 2]),
      ],
      outputs: [
        TensorSpec(name: "staging_logits", shape: [1, 4, 1800]),
        TensorSpec(name: "apnea_logits", shape: [1, 1, 1800]),
      ]
    ),
    "sleepnet_bdi_v3": Entry(
      slug: "sleepnet_bdi_v3",
      admittedSHA256: "911c44310cd6a04deba5d9eb716bc92b387cc539b81211ff7dde690b9747d0c4",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "high_res", shape: [1, 115200, 2]),
      ],
      outputs: [
        TensorSpec(name: "staging_logits", shape: [1, 4, 1800]),
        TensorSpec(name: "apnea_logits", shape: [1, 1, 1800]),
      ]
    ),
    "sleepnet_moonstone": Entry(
      slug: "sleepnet_moonstone",
      admittedSHA256: "74450f57791b41af9b30ab97f883af11996ab0b3a95501630ed93f51dee146ca",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "high_res", shape: [1, 115200, 3]),
        TensorSpec(name: "low_res", shape: [1, 1800, 1]),
      ],
      outputs: [
        TensorSpec(name: "staging_logits", shape: [1, 4, 1800]),
        TensorSpec(name: "apnea_logits", shape: [1, 1, 1800]),
      ]
    ),
    "source_embedding": Entry(
      slug: "source_embedding",
      admittedSHA256: "0c63d3c6e643cdae7b004a4dd171705e096b737bd916bd7b1f7c657cda55e478",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "source_ids", shape: [1, 16]),
      ],
      outputs: [
        TensorSpec(name: "source_features", shape: [1, 16, 8]),
      ]
    ),
    "step_eligibility": Entry(
      slug: "step_eligibility",
      admittedSHA256: "7a687c7e85736fa3e8668f90f13650e6248f649f1691c79f9c9690e5f77b6095",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "motion", shape: [1, 19]),
      ],
      outputs: [
        TensorSpec(name: "eligibility_features", shape: [1, 4]),
      ]
    ),
    "step_head": Entry(
      slug: "step_head",
      admittedSHA256: "e84b32bb41998dbe48102063e3acd660a4ba394b6d037b86e7c25bd503b806c9",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "eligibility_features", shape: [1, 4]),
      ],
      outputs: [
        TensorSpec(name: "eligibility", shape: [1, 1]),
      ]
    ),
    "step_multiplier": Entry(
      slug: "step_multiplier",
      admittedSHA256: "7861cf28e0c8d045319a58a4f4055e3ee70cbe92d763e62b4f23f834cd8bda89",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "eligibility", shape: [1, 1]),
      ],
      outputs: [
        TensorSpec(name: "multiplier", shape: [1, 1]),
      ]
    ),
    "whr_unet_encoder": Entry(
      slug: "whr_unet_encoder",
      admittedSHA256: "fb6779598f631eeca2ceaa1e4909d05508911532f317304c580634cbdee04172",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "images", shape: [1, 4, 128, 128]),
      ],
      outputs: [
        TensorSpec(name: "features", shape: [1, 2, 128, 128]),
      ]
    ),
    "whr_unet_head": Entry(
      slug: "whr_unet_head",
      admittedSHA256: "90a6898d07507935ee69b6bfb3e85280190303db830ebea99fe3123c245ae5d7",
      computeUnits: .all,
      inputs: [
        TensorSpec(name: "vectors", shape: [1, 1, 128]),
        TensorSpec(name: "scalars", shape: [1, 7]),
        TensorSpec(name: "features", shape: [1, 2, 128, 128]),
      ],
      outputs: [
        TensorSpec(name: "heart_rate", shape: [1, 2, 128]),
      ]
    ),
  ]

  static let slugs: [String] = [
    "activity_context_embedding",
    "activity_detection",
    "activity_ensemble",
    "activity_history_transformer",
    "activity_primary_segments",
    "activity_secondary_segments",
    "activity_transition",
    "awhr_imputation",
    "awhr_profile_core",
    "awhr_profile_head",
    "awhr_profile_recurrent",
    "behavior_embedding",
    "cva_encoder",
    "cva_predictor_v1_base",
    "cva_probes_female",
    "cva_probes_male",
    "dhrv_imputation",
    "energy_expenditure_hr",
    "energy_expenditure_no_hr",
    "halite_ppg_score",
    "halite_risk_tree",
    "illness_detection",
    "popsicle_min_follicular",
    "popsicle_min_follicular_v16",
    "popsicle_ovulation_detection",
    "popsicle_ovulation_detection_v16",
    "popsicle_ovulation_prediction",
    "popsicle_ovulation_prediction_v16",
    "popsicle_period_prediction",
    "popsicle_period_prediction_v16",
    "pulse_ppg",
    "pulsenet_foundation",
    "sleepnet_bdi",
    "sleepnet_bdi_v3",
    "sleepnet_moonstone",
    "source_embedding",
    "step_eligibility",
    "step_head",
    "step_multiplier",
    "whr_unet_encoder",
    "whr_unet_head",
  ]
}
