#!/usr/bin/env python3
"""Every generated file that is also committed still matches the source it is generated from.

A file that says "Do not edit" at the top and is checked into Git is a promise, and the only thing
that keeps a promise like that is a gate. Three generators already had a `--check` mode, but they
were wired into CI one step at a time and not into the local pre-commit list, so the answer to "did
I regenerate that?" was whoever remembered.

The fourth had no gate at all. `apps/ios/Maverick.xcodeproj` is generated by XcodeGen from
`apps/ios/project.yml` and committed beside it; adding a test fixture to the spec and forgetting to
regenerate produced a project that silently did not carry the fixture, and nothing said so. That is
the failure this file exists for.

    tools/check_generated.py            fail if anything is stale
    tools/check_generated.py --write    regenerate everything in place

XcodeGen is optional: it is a Homebrew tool rather than a repo dependency, so its absence is
reported and skipped rather than failing a Linux docs job. Everything else is Python and always
runs.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: Generators that own their own `--check`. Each is (label, check command, write command).
PYTHON_GENERATORS = [
    (
        "design tokens (tokens/aura.json)",
        [sys.executable, "tools/gen_design_tokens.py", "--check"],
        [sys.executable, "tools/gen_design_tokens.py"],
    ),
    (
        "model bindings (artifacts/models/manifest.json)",
        [sys.executable, "tools/ml/generate_bindings.py", "--check"],
        [sys.executable, "tools/ml/generate_bindings.py"],
    ),
    (
        "precision ledger (artifacts/models/manifest.json)",
        [sys.executable, "tools/ml/build_ledger.py", "--check"],
        [sys.executable, "tools/ml/build_ledger.py"],
    ),
]

XCODE_PROJECT = ROOT / "apps/ios/Maverick.xcodeproj"
XCODE_SPEC = ROOT / "apps/ios/project.yml"


def run(command: list[str], cwd: Path = ROOT) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=cwd, text=True, capture_output=True)


def check_xcode_project(write: bool) -> str | None:
    """Regenerate the Xcode project in place and report whether that changed anything.

    In place rather than into a scratch copy because the spec resolves source paths outside
    `apps/ios` — the shared fixtures — so a copy of `apps/ios` alone cannot generate a comparable
    project. The before/after comparison is of the file's own bytes rather than of `git diff`, so
    an already-regenerated-but-uncommitted project reads as in sync, which is what it is.
    """
    if shutil.which("xcodegen") is None:
        print("check_generated: xcodegen not installed, skipping the Xcode project", file=sys.stderr)
        return None
    project = XCODE_PROJECT / "project.pbxproj"
    before = project.read_text() if project.is_file() else None
    result = run(["xcodegen", "generate", "--quiet"], cwd=XCODE_SPEC.parent)
    if result.returncode != 0:
        return f"xcodegen failed: {(result.stderr or result.stdout).strip()}"
    if write or before is None:
        return None
    if project.read_text() != before:
        return (
            "apps/ios/Maverick.xcodeproj was stale against apps/ios/project.yml and has been "
            "regenerated; review and commit it"
        )
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write", action="store_true", help="regenerate in place instead of checking"
    )
    args = parser.parse_args()

    failures: list[str] = []
    for label, check, write in PYTHON_GENERATORS:
        result = run(write if args.write else check)
        if result.returncode != 0:
            detail = (result.stderr or result.stdout).strip().splitlines()
            failures.append(f"{label}: {detail[0] if detail else 'failed'}")

    problem = check_xcode_project(args.write)
    if problem:
        failures.append(problem)

    for line in failures:
        print(f"check_generated: {line}", file=sys.stderr)
    if failures:
        return 1
    print(f"check_generated: ok, {len(PYTHON_GENERATORS) + 1} generated outputs match their sources")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
