#!/usr/bin/env python3
"""Generate the Aura theme constants for both platforms from tokens/aura.json.

Stdlib only, and deterministic: the same input produces byte-identical output, so CI can
regenerate and fail on `git diff --exit-code`. The generated files are committed, because a
developer opening the theme should see the values, not a build step.

What this owns is the *values* — colours, spacing, radii, and the type scale's sizes. What it
deliberately does not own is anything a platform genuinely decides: font families, weight names,
and how a scheme is resolved at runtime. Those stay in the hand-written theme file that consumes
these constants.

    tools/gen_design_tokens.py            write the generated files
    tools/gen_design_tokens.py --check    exit 1 if regenerating would change anything
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "tokens" / "aura.json"
SWIFT_OUT = ROOT / "apps/ios/Maverick/UI/AuraTokens.generated.swift"
KOTLIN_OUT = ROOT / "apps/android/app/src/main/java/com/sennnen/mav/ui/aura/AuraTokens.generated.kt"

BANNER = "Generated by tools/gen_design_tokens.py from tokens/aura.json. Do not edit."


def load(path: Path) -> dict:
    return json.loads(path.read_text())


def strip_comments(value):
    """Drop the `$comment` keys so a documentation edit never reorders generated output."""
    if isinstance(value, dict):
        return {k: strip_comments(v) for k, v in value.items() if k != "$comment"}
    return value


def swift(tokens: dict) -> str:
    out = [f"// {BANNER}", "", "import CoreGraphics", "", "enum AuraTokens {"]

    out.append("  // Colours: (dark, light) as RGB hex.")
    for name, pair in tokens["colors"].items():
        out.append(
            f"  static let {name}: (dark: UInt32, light: UInt32) ="
            f" (0x{pair['dark']}, 0x{pair['light']})"
        )
    out.append("")

    out.append("  // Colours identical in both schemes.")
    for name, value in tokens["fixedColors"].items():
        out.append(f"  static let {name}: UInt32 = 0x{value}")
    out.append("")

    out.append("  // Colours carrying an alpha per scheme.")
    for name, pair in tokens["alphaColors"].items():
        dark_hex, dark_a = pair["dark"]
        light_hex, light_a = pair["light"]
        out.append(
            f"  static let {name}: (dark: (UInt32, CGFloat), light: (UInt32, CGFloat)) ="
            f" ((0x{dark_hex}, {dark_a}), (0x{light_hex}, {light_a}))"
        )
    out.append("")

    out.append("  // Metric family hues: glow centre and the edge it blooms out of.")
    for family in tokens["families"]["order"]:
        entry = tokens["families"][family]
        for role in ("glow", "edge"):
            pair = entry[role]
            key = f"{family}{role.capitalize()}"
            out.append(
                f"  static let {key}: (dark: UInt32, light: UInt32) ="
                f" (0x{pair['dark']}, 0x{pair['light']})"
            )
    out.append("")

    for section, kind in (("spacing", "CGFloat"), ("radii", "CGFloat"), ("typeScale", "CGFloat")):
        out.append(f"  // {section}")
        for name, value in tokens[section].items():
            key = name if section != "radii" else f"{name}Radius"
            out.append(f"  static let {key}: {kind} = {value}")
        out.append("")

    out.append("}")
    return "\n".join(out).rstrip("\n") + "\n"


def kotlin(tokens: dict) -> str:
    out = [
        f"// {BANNER}",
        "",
        "package com.sennnen.mav.ui.aura",
        "",
        "import androidx.compose.ui.unit.Dp",
        "import androidx.compose.ui.unit.TextUnit",
        "import androidx.compose.ui.unit.dp",
        "import androidx.compose.ui.unit.sp",
        "",
        "object AuraTokens {",
    ]

    out.append("    // Colours: RGB hex, resolved per scheme by the palette.")
    for name, pair in tokens["colors"].items():
        out.append(f"    const val {name}Dark: Long = 0x{pair['dark']}")
        out.append(f"    const val {name}Light: Long = 0x{pair['light']}")
    out.append("")

    out.append("    // Colours identical in both schemes.")
    for name, value in tokens["fixedColors"].items():
        out.append(f"    const val {name}: Long = 0x{value}")
    out.append("")

    out.append("    // Colours carrying an alpha per scheme.")
    for name, pair in tokens["alphaColors"].items():
        dark_hex, dark_a = pair["dark"]
        light_hex, light_a = pair["light"]
        out.append(f"    const val {name}Dark: Long = 0x{dark_hex}")
        out.append(f"    const val {name}DarkAlpha: Float = {dark_a}f")
        out.append(f"    const val {name}Light: Long = 0x{light_hex}")
        out.append(f"    const val {name}LightAlpha: Float = {light_a}f")
    out.append("")

    out.append("    // Metric family hues: glow centre and the edge it blooms out of.")
    for family in tokens["families"]["order"]:
        entry = tokens["families"][family]
        for role in ("glow", "edge"):
            pair = entry[role]
            key = f"{family}{role.capitalize()}"
            out.append(f"    const val {key}Dark: Long = 0x{pair['dark']}")
            out.append(f"    const val {key}Light: Long = 0x{pair['light']}")
    out.append("")

    out.append("    // spacing")
    for name, value in tokens["spacing"].items():
        out.append(f"    val {name}: Dp = {value}.dp")
    out.append("")

    out.append("    // radii")
    for name, value in tokens["radii"].items():
        out.append(f"    val {name}Radius: Dp = {value}.dp")
    out.append("")

    out.append("    // type scale")
    for name, value in tokens["typeScale"].items():
        out.append(f"    val {name}Size: TextUnit = {value}.sp")

    out.append("}")
    return "\n".join(out).rstrip("\n") + "\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    tokens = strip_comments(load(TOKENS))
    generated = {SWIFT_OUT: swift(tokens), KOTLIN_OUT: kotlin(tokens)}

    stale = []
    for path, content in generated.items():
        if check:
            if not path.is_file() or path.read_text() != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)

    if check:
        for path in stale:
            print(f"gen_design_tokens: stale {path.relative_to(ROOT)}", file=sys.stderr)
        if stale:
            print(
                "gen_design_tokens: run tools/gen_design_tokens.py and commit the result",
                file=sys.stderr,
            )
            return 1
        print("gen_design_tokens: generated files match tokens/aura.json")
    else:
        for path in generated:
            print(f"gen_design_tokens: wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
