//! The half of the zoo that runs as Rust rather than as a converted artefact.
//!
//! Twelve of the thirty-one training archives contain no weights at all. They are
//! TorchScript because that is what the training pipeline emits, but what they hold is
//! arithmetic: threshold tables, weighted averages, medians, scaling curves. There is no
//! tensor for an accelerator to accelerate.
//!
//! So they are not converted. [`super`] explains why the neural cores go to Core ML and
//! TensorFlow Lite; the same reasoning sends these the other way. Shipping a weighted
//! average as an `.mlpackage` would add a platform runtime, an FFI round trip and an
//! artefact hash to guard, in exchange for nothing — and it would put the arithmetic
//! somewhere neither platform can golden-vector test it.
//!
//! Each module here is a faithful port of one archive, with the exact tables and the exact
//! branch order, tested against vectors generated from the archive itself. Where the
//! original computes in a narrower precision than its inputs, the port reproduces that
//! too: matching the reference matters more than being tidy.
//!
//! All twelve are ported: [`astd_event_detection`], [`atlas_trendline`],
//! [`cumulative_stress`], [`cva_calibrator`], [`daily_medians`], [`daytime_stress`],
//! [`meal_timing`], [`pregnancy_biometrics`], [`short_term_baselines`],
//! [`steps_motion_decoder`], [`stress_resilience`], [`training_stress_score`].
//!
//! [`atlas`] is here too and is the exception that proves the rule: it *does* hold weights —
//! sixty of them, across twelve linear regressions. Sixty coefficients in dot products of at
//! most five terms is not work an accelerator can help with, so the same reasoning applies
//! and it takes the same route.
//!
//! Each port's golden vectors live in `artifacts/models/vectors/` and are generated by
//! `tools/ml/deterministic_vectors.py`, which runs the archive itself. Regenerate them
//! there rather than editing them; see docs/testing.md.

pub mod astd_event_detection;
pub mod atlas;
pub mod atlas_trendline;
pub mod cumulative_stress;
pub mod cva_calibrator;
pub mod daily_medians;
pub mod daytime_stress;
pub mod meal_timing;
pub mod pregnancy_biometrics;
pub mod pregnancy_tables;
pub mod short_term_baselines;
pub mod steps_motion_decoder;
pub mod stress_resilience;
pub mod training_stress_score;

/// The median as `torch.median` computes it: for an even count, the lower of the two
/// middle values rather than their mean.
///
/// Every port here needs it, and getting it wrong shifts a baseline by half a step on
/// exactly the even-length inputs a short history produces.
pub(crate) fn torch_median(values: &[f64]) -> Option<f64> {
    if values.is_empty() {
        return None;
    }
    let mut sorted: Vec<f64> = values.to_vec();
    sorted.sort_by(|a, b| a.partial_cmp(b).unwrap_or(core::cmp::Ordering::Equal));
    Some(sorted[(sorted.len() - 1) / 2])
}

/// The median as NumPy computes it: for an even count, the mean of the two middle values.
///
/// Two archives want this one instead, and both reach it the same roundabout way — taking
/// `torch.median` of the values, again with the maximum appended, and averaging the two.
/// Appending the maximum shifts an even-length input's lower-middle up to the upper-middle,
/// so the average of the two calls is the average of the middle pair. The port computes it
/// directly; the identity is why the two agree.
pub(crate) fn numpy_median(values: &[f64]) -> Option<f64> {
    if values.is_empty() {
        return None;
    }
    let mut sorted: Vec<f64> = values.to_vec();
    sorted.sort_by(|a, b| a.partial_cmp(b).unwrap_or(core::cmp::Ordering::Equal));
    let middle = sorted.len() / 2;
    if sorted.len() % 2 == 1 {
        Some(sorted[middle])
    } else {
        Some((sorted[middle - 1] + sorted[middle]) / 2.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn median_of_an_odd_count_is_the_middle_value() {
        assert_eq!(torch_median(&[53.0, 54.0, 55.0, 56.0, 57.0]), Some(55.0));
    }

    #[test]
    fn median_of_an_even_count_is_the_lower_middle_not_the_mean() {
        // The mean of the middle pair would be 55.0. torch.median returns 54.0, and a
        // baseline that used the mean would drift from the reference on every even history.
        assert_eq!(torch_median(&[53.0, 54.0, 56.0, 57.0]), Some(54.0));
    }

    #[test]
    fn median_of_nothing_is_nothing() {
        assert_eq!(torch_median(&[]), None);
    }
}
